<?php

/**
 * Public_MensajesParticipantes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    siglas-(institucion)
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Public_MensajesParticipantes extends BasePublic_MensajesParticipantes
{
    public function save(Doctrine_Connection $conn = null)
    {
        $this->setMensajesGrupoId(sfContext::getInstance()->getUser()->getAttribute('mensajes_grupo_id'));

        return parent::save($conn);
    }
}
