<?php

/**
 * Vehiculos_ConductorVehiculo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    siglas
 * @subpackage model
 * @author     Livio Lopez
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Vehiculos_ConductorVehiculo extends BaseVehiculos_ConductorVehiculo
{
}
