<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/05/19 00:00:44

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'pgsql:host=127.0.0.1;dbname=correspondencia_mat',
  'username' => 'postgres',
  'password' => 'postgres',
  'name' => 'doctrine',
)),);
