<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Vehiculos_Vehiculo', 'doctrine');

/**
 * BaseVehiculos_Vehiculo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $tipo_uso_id
 * @property integer $tipo_id
 * @property string $placa
 * @property integer $ano
 * @property string $marca
 * @property string $modelo
 * @property string $serial_carroceria
 * @property string $serial_motor
 * @property string $color
 * @property integer $kilometraje_inicial
 * @property integer $kilometraje_actual
 * @property integer $vel_max
 * @property string $status
 * @property integer $id_update
 * @property integer $id_create
 * @property string $ip_update
 * @property string $ip_create
 * @property Vehiculos_TipoUso $Vehiculos_TipoUso
 * @property Vehiculos_Tipo $Vehiculos_Tipo
 * @property Doctrine_Collection $Vehiculos_ConductorVehiculo
 * @property Doctrine_Collection $Vehiculos_GpsVehiculo
 * @property Doctrine_Collection $Vehiculos_Mantenimiento
 * 
 * @method integer             getId()                          Returns the current record's "id" value
 * @method integer             getTipoUsoId()                   Returns the current record's "tipo_uso_id" value
 * @method integer             getTipoId()                      Returns the current record's "tipo_id" value
 * @method string              getPlaca()                       Returns the current record's "placa" value
 * @method integer             getAno()                         Returns the current record's "ano" value
 * @method string              getMarca()                       Returns the current record's "marca" value
 * @method string              getModelo()                      Returns the current record's "modelo" value
 * @method string              getSerialCarroceria()            Returns the current record's "serial_carroceria" value
 * @method string              getSerialMotor()                 Returns the current record's "serial_motor" value
 * @method string              getColor()                       Returns the current record's "color" value
 * @method integer             getKilometrajeInicial()          Returns the current record's "kilometraje_inicial" value
 * @method integer             getKilometrajeActual()           Returns the current record's "kilometraje_actual" value
 * @method integer             getVelMax()                      Returns the current record's "vel_max" value
 * @method string              getStatus()                      Returns the current record's "status" value
 * @method integer             getIdUpdate()                    Returns the current record's "id_update" value
 * @method integer             getIdCreate()                    Returns the current record's "id_create" value
 * @method string              getIpUpdate()                    Returns the current record's "ip_update" value
 * @method string              getIpCreate()                    Returns the current record's "ip_create" value
 * @method Vehiculos_TipoUso   getVehiculosTipoUso()            Returns the current record's "Vehiculos_TipoUso" value
 * @method Vehiculos_Tipo      getVehiculosTipo()               Returns the current record's "Vehiculos_Tipo" value
 * @method Doctrine_Collection getVehiculosConductorVehiculo()  Returns the current record's "Vehiculos_ConductorVehiculo" collection
 * @method Doctrine_Collection getVehiculosGpsVehiculo()        Returns the current record's "Vehiculos_GpsVehiculo" collection
 * @method Doctrine_Collection getVehiculosMantenimiento()      Returns the current record's "Vehiculos_Mantenimiento" collection
 * @method Vehiculos_Vehiculo  setId()                          Sets the current record's "id" value
 * @method Vehiculos_Vehiculo  setTipoUsoId()                   Sets the current record's "tipo_uso_id" value
 * @method Vehiculos_Vehiculo  setTipoId()                      Sets the current record's "tipo_id" value
 * @method Vehiculos_Vehiculo  setPlaca()                       Sets the current record's "placa" value
 * @method Vehiculos_Vehiculo  setAno()                         Sets the current record's "ano" value
 * @method Vehiculos_Vehiculo  setMarca()                       Sets the current record's "marca" value
 * @method Vehiculos_Vehiculo  setModelo()                      Sets the current record's "modelo" value
 * @method Vehiculos_Vehiculo  setSerialCarroceria()            Sets the current record's "serial_carroceria" value
 * @method Vehiculos_Vehiculo  setSerialMotor()                 Sets the current record's "serial_motor" value
 * @method Vehiculos_Vehiculo  setColor()                       Sets the current record's "color" value
 * @method Vehiculos_Vehiculo  setKilometrajeInicial()          Sets the current record's "kilometraje_inicial" value
 * @method Vehiculos_Vehiculo  setKilometrajeActual()           Sets the current record's "kilometraje_actual" value
 * @method Vehiculos_Vehiculo  setVelMax()                      Sets the current record's "vel_max" value
 * @method Vehiculos_Vehiculo  setStatus()                      Sets the current record's "status" value
 * @method Vehiculos_Vehiculo  setIdUpdate()                    Sets the current record's "id_update" value
 * @method Vehiculos_Vehiculo  setIdCreate()                    Sets the current record's "id_create" value
 * @method Vehiculos_Vehiculo  setIpUpdate()                    Sets the current record's "ip_update" value
 * @method Vehiculos_Vehiculo  setIpCreate()                    Sets the current record's "ip_create" value
 * @method Vehiculos_Vehiculo  setVehiculosTipoUso()            Sets the current record's "Vehiculos_TipoUso" value
 * @method Vehiculos_Vehiculo  setVehiculosTipo()               Sets the current record's "Vehiculos_Tipo" value
 * @method Vehiculos_Vehiculo  setVehiculosConductorVehiculo()  Sets the current record's "Vehiculos_ConductorVehiculo" collection
 * @method Vehiculos_Vehiculo  setVehiculosGpsVehiculo()        Sets the current record's "Vehiculos_GpsVehiculo" collection
 * @method Vehiculos_Vehiculo  setVehiculosMantenimiento()      Sets the current record's "Vehiculos_Mantenimiento" collection
 * 
 * @package    siglas
 * @subpackage model
 * @author     Livio Lopez
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVehiculos_Vehiculo extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vehiculos.vehiculo');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'vehiculos.vehiculo_id',
             'length' => 4,
             ));
        $this->hasColumn('tipo_uso_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('tipo_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('placa', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 50,
             ));
        $this->hasColumn('ano', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('marca', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 50,
             ));
        $this->hasColumn('modelo', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 50,
             ));
        $this->hasColumn('serial_carroceria', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 50,
             ));
        $this->hasColumn('serial_motor', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 50,
             ));
        $this->hasColumn('color', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 50,
             ));
        $this->hasColumn('kilometraje_inicial', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('kilometraje_actual', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('vel_max', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('status', 'string', 1, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('id_update', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_create', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('ip_update', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 50,
             ));
        $this->hasColumn('ip_create', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Vehiculos_TipoUso', array(
             'local' => 'tipo_uso_id',
             'foreign' => 'id'));

        $this->hasOne('Vehiculos_Tipo', array(
             'local' => 'tipo_id',
             'foreign' => 'id'));

        $this->hasMany('Vehiculos_ConductorVehiculo', array(
             'local' => 'id',
             'foreign' => 'vehiculo_id'));

        $this->hasMany('Vehiculos_GpsVehiculo', array(
             'local' => 'id',
             'foreign' => 'vehiculo_id'));

        $this->hasMany('Vehiculos_Mantenimiento', array(
             'local' => 'id',
             'foreign' => 'vehiculo_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}