<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Vehiculos_Mantenimiento', 'doctrine');

/**
 * BaseVehiculos_Mantenimiento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $vehiculo_id
 * @property integer $mantenimiento_tipo_id
 * @property string $observacion
 * @property integer $kilometraje
 * @property timestamp $fecha
 * @property string $status
 * @property integer $id_update
 * @property integer $id_create
 * @property string $ip_update
 * @property string $ip_create
 * @property Vehiculos_Vehiculo $Vehiculos_Vehiculo
 * @property Vehiculos_MantenimientoTipo $Vehiculos_MantenimientoTipo
 * 
 * @method integer                     getId()                          Returns the current record's "id" value
 * @method integer                     getVehiculoId()                  Returns the current record's "vehiculo_id" value
 * @method integer                     getMantenimientoTipoId()         Returns the current record's "mantenimiento_tipo_id" value
 * @method string                      getObservacion()                 Returns the current record's "observacion" value
 * @method integer                     getKilometraje()                 Returns the current record's "kilometraje" value
 * @method timestamp                   getFecha()                       Returns the current record's "fecha" value
 * @method string                      getStatus()                      Returns the current record's "status" value
 * @method integer                     getIdUpdate()                    Returns the current record's "id_update" value
 * @method integer                     getIdCreate()                    Returns the current record's "id_create" value
 * @method string                      getIpUpdate()                    Returns the current record's "ip_update" value
 * @method string                      getIpCreate()                    Returns the current record's "ip_create" value
 * @method Vehiculos_Vehiculo          getVehiculosVehiculo()           Returns the current record's "Vehiculos_Vehiculo" value
 * @method Vehiculos_MantenimientoTipo getVehiculosMantenimientoTipo()  Returns the current record's "Vehiculos_MantenimientoTipo" value
 * @method Vehiculos_Mantenimiento     setId()                          Sets the current record's "id" value
 * @method Vehiculos_Mantenimiento     setVehiculoId()                  Sets the current record's "vehiculo_id" value
 * @method Vehiculos_Mantenimiento     setMantenimientoTipoId()         Sets the current record's "mantenimiento_tipo_id" value
 * @method Vehiculos_Mantenimiento     setObservacion()                 Sets the current record's "observacion" value
 * @method Vehiculos_Mantenimiento     setKilometraje()                 Sets the current record's "kilometraje" value
 * @method Vehiculos_Mantenimiento     setFecha()                       Sets the current record's "fecha" value
 * @method Vehiculos_Mantenimiento     setStatus()                      Sets the current record's "status" value
 * @method Vehiculos_Mantenimiento     setIdUpdate()                    Sets the current record's "id_update" value
 * @method Vehiculos_Mantenimiento     setIdCreate()                    Sets the current record's "id_create" value
 * @method Vehiculos_Mantenimiento     setIpUpdate()                    Sets the current record's "ip_update" value
 * @method Vehiculos_Mantenimiento     setIpCreate()                    Sets the current record's "ip_create" value
 * @method Vehiculos_Mantenimiento     setVehiculosVehiculo()           Sets the current record's "Vehiculos_Vehiculo" value
 * @method Vehiculos_Mantenimiento     setVehiculosMantenimientoTipo()  Sets the current record's "Vehiculos_MantenimientoTipo" value
 * 
 * @package    siglas
 * @subpackage model
 * @author     Livio Lopez
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVehiculos_Mantenimiento extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vehiculos.mantenimiento');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'vehiculos.mantenimiento_id',
             'length' => 4,
             ));
        $this->hasColumn('vehiculo_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('mantenimiento_tipo_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('observacion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('kilometraje', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('status', 'string', 1, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('id_update', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_create', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('ip_update', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 50,
             ));
        $this->hasColumn('ip_create', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Vehiculos_Vehiculo', array(
             'local' => 'vehiculo_id',
             'foreign' => 'id'));

        $this->hasOne('Vehiculos_MantenimientoTipo', array(
             'local' => 'mantenimiento_tipo_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}