<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Vehiculos_Comando', 'doctrine');

/**
 * BaseVehiculos_Comando
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $comando
 * @property string $descripcion
 * @property integer $gps_id
 * @property string $status
 * @property integer $id_update
 * @property integer $id_create
 * @property string $ip_update
 * @property string $ip_create
 * @property Vehiculos_Gps $Vehiculos_Gps
 * 
 * @method integer           getId()            Returns the current record's "id" value
 * @method string            getComando()       Returns the current record's "comando" value
 * @method string            getDescripcion()   Returns the current record's "descripcion" value
 * @method integer           getGpsId()         Returns the current record's "gps_id" value
 * @method string            getStatus()        Returns the current record's "status" value
 * @method integer           getIdUpdate()      Returns the current record's "id_update" value
 * @method integer           getIdCreate()      Returns the current record's "id_create" value
 * @method string            getIpUpdate()      Returns the current record's "ip_update" value
 * @method string            getIpCreate()      Returns the current record's "ip_create" value
 * @method Vehiculos_Gps     getVehiculosGps()  Returns the current record's "Vehiculos_Gps" value
 * @method Vehiculos_Comando setId()            Sets the current record's "id" value
 * @method Vehiculos_Comando setComando()       Sets the current record's "comando" value
 * @method Vehiculos_Comando setDescripcion()   Sets the current record's "descripcion" value
 * @method Vehiculos_Comando setGpsId()         Sets the current record's "gps_id" value
 * @method Vehiculos_Comando setStatus()        Sets the current record's "status" value
 * @method Vehiculos_Comando setIdUpdate()      Sets the current record's "id_update" value
 * @method Vehiculos_Comando setIdCreate()      Sets the current record's "id_create" value
 * @method Vehiculos_Comando setIpUpdate()      Sets the current record's "ip_update" value
 * @method Vehiculos_Comando setIpCreate()      Sets the current record's "ip_create" value
 * @method Vehiculos_Comando setVehiculosGps()  Sets the current record's "Vehiculos_Gps" value
 * 
 * @package    siglas
 * @subpackage model
 * @author     Livio Lopez
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVehiculos_Comando extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vehiculos.comando');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'vehiculos.comando_id',
             'length' => 4,
             ));
        $this->hasColumn('comando', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 200,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('gps_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('status', 'string', 1, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('id_update', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_create', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('ip_update', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 50,
             ));
        $this->hasColumn('ip_create', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Vehiculos_Gps', array(
             'local' => 'gps_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}