<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Public_TipoEducacionAdicional', 'doctrine');

/**
 * BasePublic_TipoEducacionAdicional
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property string $status
 * @property integer $id_update
 * @property Doctrine_Collection $Funcionarios_EducacionAdicional
 * 
 * @method integer                       getId()                              Returns the current record's "id" value
 * @method string                        getNombre()                          Returns the current record's "nombre" value
 * @method string                        getStatus()                          Returns the current record's "status" value
 * @method integer                       getIdUpdate()                        Returns the current record's "id_update" value
 * @method Doctrine_Collection           getFuncionariosEducacionAdicional()  Returns the current record's "Funcionarios_EducacionAdicional" collection
 * @method Public_TipoEducacionAdicional setId()                              Sets the current record's "id" value
 * @method Public_TipoEducacionAdicional setNombre()                          Sets the current record's "nombre" value
 * @method Public_TipoEducacionAdicional setStatus()                          Sets the current record's "status" value
 * @method Public_TipoEducacionAdicional setIdUpdate()                        Sets the current record's "id_update" value
 * @method Public_TipoEducacionAdicional setFuncionariosEducacionAdicional()  Sets the current record's "Funcionarios_EducacionAdicional" collection
 * 
 * @package    siglas
 * @subpackage model
 * @author     Livio Lopez
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePublic_TipoEducacionAdicional extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('public.tipo_educacion_adicional');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'public.tipo_educacion_adicional_id',
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('status', 'string', 1, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('id_update', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Funcionarios_EducacionAdicional', array(
             'local' => 'id',
             'foreign' => 'tipo_educacion_adicional_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}