<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Public_TipoCuenta', 'doctrine');

/**
 * BasePublic_TipoCuenta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property integer $id_update
 * 
 * @method integer           getId()        Returns the current record's "id" value
 * @method string            getNombre()    Returns the current record's "nombre" value
 * @method integer           getIdUpdate()  Returns the current record's "id_update" value
 * @method Public_TipoCuenta setId()        Sets the current record's "id" value
 * @method Public_TipoCuenta setNombre()    Sets the current record's "nombre" value
 * @method Public_TipoCuenta setIdUpdate()  Sets the current record's "id_update" value
 * 
 * @package    siglas
 * @subpackage model
 * @author     Livio Lopez
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePublic_TipoCuenta extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('public.tipo_cuenta');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'public.tipo_cuenta_id',
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('id_update', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}