<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Public_NivelInstruccion', 'doctrine');

/**
 * BasePublic_NivelInstruccion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property string $tipo
 * @property string $status
 * @property integer $id_update
 * 
 * @method integer                 getId()        Returns the current record's "id" value
 * @method string                  getNombre()    Returns the current record's "nombre" value
 * @method string                  getTipo()      Returns the current record's "tipo" value
 * @method string                  getStatus()    Returns the current record's "status" value
 * @method integer                 getIdUpdate()  Returns the current record's "id_update" value
 * @method Public_NivelInstruccion setId()        Sets the current record's "id" value
 * @method Public_NivelInstruccion setNombre()    Sets the current record's "nombre" value
 * @method Public_NivelInstruccion setTipo()      Sets the current record's "tipo" value
 * @method Public_NivelInstruccion setStatus()    Sets the current record's "status" value
 * @method Public_NivelInstruccion setIdUpdate()  Sets the current record's "id_update" value
 * 
 * @package    siglas
 * @subpackage model
 * @author     Livio Lopez
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePublic_NivelInstruccion extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('public.nivel_instruccion');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'public.nivel_instruccion_id',
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('tipo', 'string', 1, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('status', 'string', 1, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('id_update', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}