<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Public_Pais', 'doctrine');

/**
 * BasePublic_Pais
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property string $siglas
 * @property Doctrine_Collection $Funcionarios_Nacionalidad
 * 
 * @method integer             getId()                        Returns the current record's "id" value
 * @method string              getNombre()                    Returns the current record's "nombre" value
 * @method string              getSiglas()                    Returns the current record's "siglas" value
 * @method Doctrine_Collection getFuncionariosNacionalidad()  Returns the current record's "Funcionarios_Nacionalidad" collection
 * @method Public_Pais         setId()                        Sets the current record's "id" value
 * @method Public_Pais         setNombre()                    Sets the current record's "nombre" value
 * @method Public_Pais         setSiglas()                    Sets the current record's "siglas" value
 * @method Public_Pais         setFuncionariosNacionalidad()  Sets the current record's "Funcionarios_Nacionalidad" collection
 * 
 * @package    siglas
 * @subpackage model
 * @author     Livio Lopez
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePublic_Pais extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('public.pais');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('siglas', 'string', 4, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Funcionarios_Nacionalidad', array(
             'local' => 'id',
             'foreign' => 'pais_id'));
    }
}