<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Public_Banco', 'doctrine');

/**
 * BasePublic_Banco
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property integer $id_update
 * @property Doctrine_Collection $Funcionarios_CuentaBancaria
 * 
 * @method integer             getId()                          Returns the current record's "id" value
 * @method string              getNombre()                      Returns the current record's "nombre" value
 * @method integer             getIdUpdate()                    Returns the current record's "id_update" value
 * @method Doctrine_Collection getFuncionariosCuentaBancaria()  Returns the current record's "Funcionarios_CuentaBancaria" collection
 * @method Public_Banco        setId()                          Sets the current record's "id" value
 * @method Public_Banco        setNombre()                      Sets the current record's "nombre" value
 * @method Public_Banco        setIdUpdate()                    Sets the current record's "id_update" value
 * @method Public_Banco        setFuncionariosCuentaBancaria()  Sets the current record's "Funcionarios_CuentaBancaria" collection
 * 
 * @package    siglas
 * @subpackage model
 * @author     Livio Lopez
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePublic_Banco extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('public.banco');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'public.banco_id',
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('id_update', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Funcionarios_CuentaBancaria', array(
             'local' => 'id',
             'foreign' => 'banco_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}