<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Public_SitioTipo', 'doctrine');

/**
 * BasePublic_SitioTipo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property string $icono
 * @property string $status
 * @property integer $id_update
 * @property integer $id_create
 * @property string $ip_update
 * @property string $ip_create
 * @property Doctrine_Collection $Public_Sitio
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getNombre()       Returns the current record's "nombre" value
 * @method string              getIcono()        Returns the current record's "icono" value
 * @method string              getStatus()       Returns the current record's "status" value
 * @method integer             getIdUpdate()     Returns the current record's "id_update" value
 * @method integer             getIdCreate()     Returns the current record's "id_create" value
 * @method string              getIpUpdate()     Returns the current record's "ip_update" value
 * @method string              getIpCreate()     Returns the current record's "ip_create" value
 * @method Doctrine_Collection getPublicSitio()  Returns the current record's "Public_Sitio" collection
 * @method Public_SitioTipo    setId()           Sets the current record's "id" value
 * @method Public_SitioTipo    setNombre()       Sets the current record's "nombre" value
 * @method Public_SitioTipo    setIcono()        Sets the current record's "icono" value
 * @method Public_SitioTipo    setStatus()       Sets the current record's "status" value
 * @method Public_SitioTipo    setIdUpdate()     Sets the current record's "id_update" value
 * @method Public_SitioTipo    setIdCreate()     Sets the current record's "id_create" value
 * @method Public_SitioTipo    setIpUpdate()     Sets the current record's "ip_update" value
 * @method Public_SitioTipo    setIpCreate()     Sets the current record's "ip_create" value
 * @method Public_SitioTipo    setPublicSitio()  Sets the current record's "Public_Sitio" collection
 * 
 * @package    siglas
 * @subpackage model
 * @author     Livio Lopez
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePublic_SitioTipo extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('public.sitio_tipo');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'public.sitio_tipo_id',
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 50,
             ));
        $this->hasColumn('icono', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 50,
             ));
        $this->hasColumn('status', 'string', 1, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('id_update', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_create', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('ip_update', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 50,
             ));
        $this->hasColumn('ip_create', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Public_Sitio', array(
             'local' => 'id',
             'foreign' => 'sitio_tipo_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}