<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Funcionarios_FuncionarioDiscapacidad', 'doctrine');

/**
 * BaseFuncionarios_FuncionarioDiscapacidad
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $funcionario_id
 * @property integer $discapacidad_id
 * @property timestamp $f_validado
 * @property integer $id_validado
 * @property string $status
 * @property integer $id_update
 * @property string $ip_update
 * @property string $proteccion
 * @property Funcionarios_Funcionario $Funcionarios_Funcionario
 * @property Public_Discapacidad $Public_Discapacidad
 * 
 * @method integer                              getId()                       Returns the current record's "id" value
 * @method integer                              getFuncionarioId()            Returns the current record's "funcionario_id" value
 * @method integer                              getDiscapacidadId()           Returns the current record's "discapacidad_id" value
 * @method timestamp                            getFValidado()                Returns the current record's "f_validado" value
 * @method integer                              getIdValidado()               Returns the current record's "id_validado" value
 * @method string                               getStatus()                   Returns the current record's "status" value
 * @method integer                              getIdUpdate()                 Returns the current record's "id_update" value
 * @method string                               getIpUpdate()                 Returns the current record's "ip_update" value
 * @method string                               getProteccion()               Returns the current record's "proteccion" value
 * @method Funcionarios_Funcionario             getFuncionariosFuncionario()  Returns the current record's "Funcionarios_Funcionario" value
 * @method Public_Discapacidad                  getPublicDiscapacidad()       Returns the current record's "Public_Discapacidad" value
 * @method Funcionarios_FuncionarioDiscapacidad setId()                       Sets the current record's "id" value
 * @method Funcionarios_FuncionarioDiscapacidad setFuncionarioId()            Sets the current record's "funcionario_id" value
 * @method Funcionarios_FuncionarioDiscapacidad setDiscapacidadId()           Sets the current record's "discapacidad_id" value
 * @method Funcionarios_FuncionarioDiscapacidad setFValidado()                Sets the current record's "f_validado" value
 * @method Funcionarios_FuncionarioDiscapacidad setIdValidado()               Sets the current record's "id_validado" value
 * @method Funcionarios_FuncionarioDiscapacidad setStatus()                   Sets the current record's "status" value
 * @method Funcionarios_FuncionarioDiscapacidad setIdUpdate()                 Sets the current record's "id_update" value
 * @method Funcionarios_FuncionarioDiscapacidad setIpUpdate()                 Sets the current record's "ip_update" value
 * @method Funcionarios_FuncionarioDiscapacidad setProteccion()               Sets the current record's "proteccion" value
 * @method Funcionarios_FuncionarioDiscapacidad setFuncionariosFuncionario()  Sets the current record's "Funcionarios_Funcionario" value
 * @method Funcionarios_FuncionarioDiscapacidad setPublicDiscapacidad()       Sets the current record's "Public_Discapacidad" value
 * 
 * @package    siglas
 * @subpackage model
 * @author     Livio Lopez
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFuncionarios_FuncionarioDiscapacidad extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('funcionarios.funcionario_discapacidad');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'funcionarios.funcionario_discapacidad_id',
             'length' => 4,
             ));
        $this->hasColumn('funcionario_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('discapacidad_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('f_validado', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('id_validado', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('status', 'string', 1, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('id_update', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('ip_update', 'string', 40, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 40,
             ));
        $this->hasColumn('proteccion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Funcionarios_Funcionario', array(
             'local' => 'funcionario_id',
             'foreign' => 'id'));

        $this->hasOne('Public_Discapacidad', array(
             'local' => 'discapacidad_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}