<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Funcionarios_InformacionCorporalFamiliar', 'doctrine');

/**
 * BaseFuncionarios_InformacionCorporalFamiliar
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $familiar_id
 * @property string $color_ojos
 * @property string $color_cabello
 * @property string $color_piel
 * @property decimal $peso
 * @property decimal $altura
 * @property string $talla_camisa
 * @property string $talla_pantalon
 * @property string $talla_calzado
 * @property string $talla_gorra
 * @property timestamp $f_validado
 * @property integer $id_validado
 * @property string $status
 * @property integer $id_update
 * @property string $ip_update
 * @property Funcionarios_Familiar $Funcionarios_Familiar
 * 
 * @method integer                                  getId()                    Returns the current record's "id" value
 * @method integer                                  getFamiliarId()            Returns the current record's "familiar_id" value
 * @method string                                   getColorOjos()             Returns the current record's "color_ojos" value
 * @method string                                   getColorCabello()          Returns the current record's "color_cabello" value
 * @method string                                   getColorPiel()             Returns the current record's "color_piel" value
 * @method decimal                                  getPeso()                  Returns the current record's "peso" value
 * @method decimal                                  getAltura()                Returns the current record's "altura" value
 * @method string                                   getTallaCamisa()           Returns the current record's "talla_camisa" value
 * @method string                                   getTallaPantalon()         Returns the current record's "talla_pantalon" value
 * @method string                                   getTallaCalzado()          Returns the current record's "talla_calzado" value
 * @method string                                   getTallaGorra()            Returns the current record's "talla_gorra" value
 * @method timestamp                                getFValidado()             Returns the current record's "f_validado" value
 * @method integer                                  getIdValidado()            Returns the current record's "id_validado" value
 * @method string                                   getStatus()                Returns the current record's "status" value
 * @method integer                                  getIdUpdate()              Returns the current record's "id_update" value
 * @method string                                   getIpUpdate()              Returns the current record's "ip_update" value
 * @method Funcionarios_Familiar                    getFuncionariosFamiliar()  Returns the current record's "Funcionarios_Familiar" value
 * @method Funcionarios_InformacionCorporalFamiliar setId()                    Sets the current record's "id" value
 * @method Funcionarios_InformacionCorporalFamiliar setFamiliarId()            Sets the current record's "familiar_id" value
 * @method Funcionarios_InformacionCorporalFamiliar setColorOjos()             Sets the current record's "color_ojos" value
 * @method Funcionarios_InformacionCorporalFamiliar setColorCabello()          Sets the current record's "color_cabello" value
 * @method Funcionarios_InformacionCorporalFamiliar setColorPiel()             Sets the current record's "color_piel" value
 * @method Funcionarios_InformacionCorporalFamiliar setPeso()                  Sets the current record's "peso" value
 * @method Funcionarios_InformacionCorporalFamiliar setAltura()                Sets the current record's "altura" value
 * @method Funcionarios_InformacionCorporalFamiliar setTallaCamisa()           Sets the current record's "talla_camisa" value
 * @method Funcionarios_InformacionCorporalFamiliar setTallaPantalon()         Sets the current record's "talla_pantalon" value
 * @method Funcionarios_InformacionCorporalFamiliar setTallaCalzado()          Sets the current record's "talla_calzado" value
 * @method Funcionarios_InformacionCorporalFamiliar setTallaGorra()            Sets the current record's "talla_gorra" value
 * @method Funcionarios_InformacionCorporalFamiliar setFValidado()             Sets the current record's "f_validado" value
 * @method Funcionarios_InformacionCorporalFamiliar setIdValidado()            Sets the current record's "id_validado" value
 * @method Funcionarios_InformacionCorporalFamiliar setStatus()                Sets the current record's "status" value
 * @method Funcionarios_InformacionCorporalFamiliar setIdUpdate()              Sets the current record's "id_update" value
 * @method Funcionarios_InformacionCorporalFamiliar setIpUpdate()              Sets the current record's "ip_update" value
 * @method Funcionarios_InformacionCorporalFamiliar setFuncionariosFamiliar()  Sets the current record's "Funcionarios_Familiar" value
 * 
 * @package    siglas
 * @subpackage model
 * @author     Livio Lopez
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFuncionarios_InformacionCorporalFamiliar extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('funcionarios.informacion_corporal_familiar');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'funcionarios.informacion_corporal_familiar_id',
             'length' => 4,
             ));
        $this->hasColumn('familiar_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('color_ojos', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 30,
             ));
        $this->hasColumn('color_cabello', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 30,
             ));
        $this->hasColumn('color_piel', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 30,
             ));
        $this->hasColumn('peso', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 18,
             ));
        $this->hasColumn('altura', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 18,
             ));
        $this->hasColumn('talla_camisa', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('talla_pantalon', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('talla_calzado', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('talla_gorra', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('f_validado', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('id_validado', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('status', 'string', 1, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('id_update', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('ip_update', 'string', 40, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 40,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Funcionarios_Familiar', array(
             'local' => 'familiar_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}