<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Funcionarios_FuncionarioEnfermedad', 'doctrine');

/**
 * BaseFuncionarios_FuncionarioEnfermedad
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $funcionario_id
 * @property integer $enfermedad_id
 * @property timestamp $f_validado
 * @property integer $id_validado
 * @property string $status
 * @property integer $id_update
 * @property string $ip_update
 * @property string $proteccion
 * @property Funcionarios_Funcionario $Funcionarios_Funcionario
 * @property Public_Enfermedad $Public_Enfermedad
 * 
 * @method integer                            getId()                       Returns the current record's "id" value
 * @method integer                            getFuncionarioId()            Returns the current record's "funcionario_id" value
 * @method integer                            getEnfermedadId()             Returns the current record's "enfermedad_id" value
 * @method timestamp                          getFValidado()                Returns the current record's "f_validado" value
 * @method integer                            getIdValidado()               Returns the current record's "id_validado" value
 * @method string                             getStatus()                   Returns the current record's "status" value
 * @method integer                            getIdUpdate()                 Returns the current record's "id_update" value
 * @method string                             getIpUpdate()                 Returns the current record's "ip_update" value
 * @method string                             getProteccion()               Returns the current record's "proteccion" value
 * @method Funcionarios_Funcionario           getFuncionariosFuncionario()  Returns the current record's "Funcionarios_Funcionario" value
 * @method Public_Enfermedad                  getPublicEnfermedad()         Returns the current record's "Public_Enfermedad" value
 * @method Funcionarios_FuncionarioEnfermedad setId()                       Sets the current record's "id" value
 * @method Funcionarios_FuncionarioEnfermedad setFuncionarioId()            Sets the current record's "funcionario_id" value
 * @method Funcionarios_FuncionarioEnfermedad setEnfermedadId()             Sets the current record's "enfermedad_id" value
 * @method Funcionarios_FuncionarioEnfermedad setFValidado()                Sets the current record's "f_validado" value
 * @method Funcionarios_FuncionarioEnfermedad setIdValidado()               Sets the current record's "id_validado" value
 * @method Funcionarios_FuncionarioEnfermedad setStatus()                   Sets the current record's "status" value
 * @method Funcionarios_FuncionarioEnfermedad setIdUpdate()                 Sets the current record's "id_update" value
 * @method Funcionarios_FuncionarioEnfermedad setIpUpdate()                 Sets the current record's "ip_update" value
 * @method Funcionarios_FuncionarioEnfermedad setProteccion()               Sets the current record's "proteccion" value
 * @method Funcionarios_FuncionarioEnfermedad setFuncionariosFuncionario()  Sets the current record's "Funcionarios_Funcionario" value
 * @method Funcionarios_FuncionarioEnfermedad setPublicEnfermedad()         Sets the current record's "Public_Enfermedad" value
 * 
 * @package    siglas
 * @subpackage model
 * @author     Livio Lopez
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFuncionarios_FuncionarioEnfermedad extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('funcionarios.funcionario_enfermedad');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'funcionarios.funcionario_enfermedad_id',
             'length' => 4,
             ));
        $this->hasColumn('funcionario_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('enfermedad_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('f_validado', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('id_validado', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('status', 'string', 1, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('id_update', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('ip_update', 'string', 40, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 40,
             ));
        $this->hasColumn('proteccion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Funcionarios_Funcionario', array(
             'local' => 'funcionario_id',
             'foreign' => 'id'));

        $this->hasOne('Public_Enfermedad', array(
             'local' => 'enfermedad_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}