<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Funcionarios_FuncionarioCargoCertificado', 'doctrine');

/**
 * BaseFuncionarios_FuncionarioCargoCertificado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $funcionario_cargo_id
 * @property string $certificado
 * @property string $detalles_tecnicos
 * @property string $configuraciones
 * @property date $f_valido_desde
 * @property date $f_valido_hasta
 * @property string $status
 * @property integer $id_update
 * @property integer $id_create
 * @property string $ip_update
 * @property Funcionarios_FuncionarioCargo $Funcionarios_FuncionarioCargo
 * 
 * @method integer                                  getId()                            Returns the current record's "id" value
 * @method integer                                  getFuncionarioCargoId()            Returns the current record's "funcionario_cargo_id" value
 * @method string                                   getCertificado()                   Returns the current record's "certificado" value
 * @method string                                   getDetallesTecnicos()              Returns the current record's "detalles_tecnicos" value
 * @method string                                   getConfiguraciones()               Returns the current record's "configuraciones" value
 * @method date                                     getFValidoDesde()                  Returns the current record's "f_valido_desde" value
 * @method date                                     getFValidoHasta()                  Returns the current record's "f_valido_hasta" value
 * @method string                                   getStatus()                        Returns the current record's "status" value
 * @method integer                                  getIdUpdate()                      Returns the current record's "id_update" value
 * @method integer                                  getIdCreate()                      Returns the current record's "id_create" value
 * @method string                                   getIpUpdate()                      Returns the current record's "ip_update" value
 * @method Funcionarios_FuncionarioCargo            getFuncionariosFuncionarioCargo()  Returns the current record's "Funcionarios_FuncionarioCargo" value
 * @method Funcionarios_FuncionarioCargoCertificado setId()                            Sets the current record's "id" value
 * @method Funcionarios_FuncionarioCargoCertificado setFuncionarioCargoId()            Sets the current record's "funcionario_cargo_id" value
 * @method Funcionarios_FuncionarioCargoCertificado setCertificado()                   Sets the current record's "certificado" value
 * @method Funcionarios_FuncionarioCargoCertificado setDetallesTecnicos()              Sets the current record's "detalles_tecnicos" value
 * @method Funcionarios_FuncionarioCargoCertificado setConfiguraciones()               Sets the current record's "configuraciones" value
 * @method Funcionarios_FuncionarioCargoCertificado setFValidoDesde()                  Sets the current record's "f_valido_desde" value
 * @method Funcionarios_FuncionarioCargoCertificado setFValidoHasta()                  Sets the current record's "f_valido_hasta" value
 * @method Funcionarios_FuncionarioCargoCertificado setStatus()                        Sets the current record's "status" value
 * @method Funcionarios_FuncionarioCargoCertificado setIdUpdate()                      Sets the current record's "id_update" value
 * @method Funcionarios_FuncionarioCargoCertificado setIdCreate()                      Sets the current record's "id_create" value
 * @method Funcionarios_FuncionarioCargoCertificado setIpUpdate()                      Sets the current record's "ip_update" value
 * @method Funcionarios_FuncionarioCargoCertificado setFuncionariosFuncionarioCargo()  Sets the current record's "Funcionarios_FuncionarioCargo" value
 * 
 * @package    siglas
 * @subpackage model
 * @author     Livio Lopez
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFuncionarios_FuncionarioCargoCertificado extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('funcionarios.funcionario_cargo_certificado');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'funcionarios.funcionario_cargo_certificado_id',
             'length' => 4,
             ));
        $this->hasColumn('funcionario_cargo_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('certificado', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('detalles_tecnicos', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('configuraciones', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('f_valido_desde', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('f_valido_hasta', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('status', 'string', 1, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('id_update', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_create', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('ip_update', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Funcionarios_FuncionarioCargo', array(
             'local' => 'funcionario_cargo_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}