<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Rrhh_VacacionesBitacora', 'doctrine');

/**
 * BaseRrhh_VacacionesBitacora
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $vacaciones_disfrutadas_id
 * @property integer $correspondencia_bitacora_id
 * @property string $tipo
 * @property integer $reposos_id
 * @property date $f_retorno_real
 * @property integer $dias_agregados_disfrute
 * @property string $status
 * @property integer $id_update
 * @property string $ip_update
 * @property Rrhh_VacacionesDisfrutadas $Rrhh_VacacionesDisfrutadas
 * @property Rrhh_Reposos $Rrhh_Reposos
 * 
 * @method integer                    getId()                          Returns the current record's "id" value
 * @method integer                    getVacacionesDisfrutadasId()     Returns the current record's "vacaciones_disfrutadas_id" value
 * @method integer                    getCorrespondenciaBitacoraId()   Returns the current record's "correspondencia_bitacora_id" value
 * @method string                     getTipo()                        Returns the current record's "tipo" value
 * @method integer                    getRepososId()                   Returns the current record's "reposos_id" value
 * @method date                       getFRetornoReal()                Returns the current record's "f_retorno_real" value
 * @method integer                    getDiasAgregadosDisfrute()       Returns the current record's "dias_agregados_disfrute" value
 * @method string                     getStatus()                      Returns the current record's "status" value
 * @method integer                    getIdUpdate()                    Returns the current record's "id_update" value
 * @method string                     getIpUpdate()                    Returns the current record's "ip_update" value
 * @method Rrhh_VacacionesDisfrutadas getRrhhVacacionesDisfrutadas()   Returns the current record's "Rrhh_VacacionesDisfrutadas" value
 * @method Rrhh_Reposos               getRrhhReposos()                 Returns the current record's "Rrhh_Reposos" value
 * @method Rrhh_VacacionesBitacora    setId()                          Sets the current record's "id" value
 * @method Rrhh_VacacionesBitacora    setVacacionesDisfrutadasId()     Sets the current record's "vacaciones_disfrutadas_id" value
 * @method Rrhh_VacacionesBitacora    setCorrespondenciaBitacoraId()   Sets the current record's "correspondencia_bitacora_id" value
 * @method Rrhh_VacacionesBitacora    setTipo()                        Sets the current record's "tipo" value
 * @method Rrhh_VacacionesBitacora    setRepososId()                   Sets the current record's "reposos_id" value
 * @method Rrhh_VacacionesBitacora    setFRetornoReal()                Sets the current record's "f_retorno_real" value
 * @method Rrhh_VacacionesBitacora    setDiasAgregadosDisfrute()       Sets the current record's "dias_agregados_disfrute" value
 * @method Rrhh_VacacionesBitacora    setStatus()                      Sets the current record's "status" value
 * @method Rrhh_VacacionesBitacora    setIdUpdate()                    Sets the current record's "id_update" value
 * @method Rrhh_VacacionesBitacora    setIpUpdate()                    Sets the current record's "ip_update" value
 * @method Rrhh_VacacionesBitacora    setRrhhVacacionesDisfrutadas()   Sets the current record's "Rrhh_VacacionesDisfrutadas" value
 * @method Rrhh_VacacionesBitacora    setRrhhReposos()                 Sets the current record's "Rrhh_Reposos" value
 * 
 * @package    siglas
 * @subpackage model
 * @author     Livio Lopez
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRrhh_VacacionesBitacora extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rrhh.vacaciones_bitacora');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'rrhh.vacaciones_bitacora_id',
             'length' => 4,
             ));
        $this->hasColumn('vacaciones_disfrutadas_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('correspondencia_bitacora_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('tipo', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('reposos_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('f_retorno_real', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('dias_agregados_disfrute', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('status', 'string', 1, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('id_update', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('ip_update', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Rrhh_VacacionesDisfrutadas', array(
             'local' => 'vacaciones_disfrutadas_id',
             'foreign' => 'id'));

        $this->hasOne('Rrhh_Reposos', array(
             'local' => 'reposos_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}