<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Rrhh_Permisos', 'doctrine');

/**
 * BaseRrhh_Permisos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $configuraciones_permisos_id
 * @property integer $funcionario_id
 * @property integer $correspondencia_solicitud_id
 * @property string $tipo_permiso
 * @property timestamp $f_inicio_permiso
 * @property timestamp $f_fin_permiso
 * @property timestamp $f_retorno_permiso
 * @property float $dias_solicitados
 * @property float $dias_permiso_habiles
 * @property integer $dias_permiso_fin_semana
 * @property integer $dias_permiso_no_laborales
 * @property float $dias_permiso_continuo
 * @property string $observaciones_descritas
 * @property string $observaciones_automaticas
 * @property integer $correspondencia_cancelacion_id
 * @property string $motivo_cancelacion
 * @property float $dias_permiso_ejecutados
 * @property string $status
 * @property integer $id_update
 * @property string $ip_update
 * @property string $clasificacion
 * @property Rrhh_Configuraciones $Rrhh_Configuraciones
 * @property Funcionarios_Funcionario $Funcionarios_Funcionario
 * 
 * @method integer                  getId()                             Returns the current record's "id" value
 * @method integer                  getConfiguracionesPermisosId()      Returns the current record's "configuraciones_permisos_id" value
 * @method integer                  getFuncionarioId()                  Returns the current record's "funcionario_id" value
 * @method integer                  getCorrespondenciaSolicitudId()     Returns the current record's "correspondencia_solicitud_id" value
 * @method string                   getTipoPermiso()                    Returns the current record's "tipo_permiso" value
 * @method timestamp                getFInicioPermiso()                 Returns the current record's "f_inicio_permiso" value
 * @method timestamp                getFFinPermiso()                    Returns the current record's "f_fin_permiso" value
 * @method timestamp                getFRetornoPermiso()                Returns the current record's "f_retorno_permiso" value
 * @method float                    getDiasSolicitados()                Returns the current record's "dias_solicitados" value
 * @method float                    getDiasPermisoHabiles()             Returns the current record's "dias_permiso_habiles" value
 * @method integer                  getDiasPermisoFinSemana()           Returns the current record's "dias_permiso_fin_semana" value
 * @method integer                  getDiasPermisoNoLaborales()         Returns the current record's "dias_permiso_no_laborales" value
 * @method float                    getDiasPermisoContinuo()            Returns the current record's "dias_permiso_continuo" value
 * @method string                   getObservacionesDescritas()         Returns the current record's "observaciones_descritas" value
 * @method string                   getObservacionesAutomaticas()       Returns the current record's "observaciones_automaticas" value
 * @method integer                  getCorrespondenciaCancelacionId()   Returns the current record's "correspondencia_cancelacion_id" value
 * @method string                   getMotivoCancelacion()              Returns the current record's "motivo_cancelacion" value
 * @method float                    getDiasPermisoEjecutados()          Returns the current record's "dias_permiso_ejecutados" value
 * @method string                   getStatus()                         Returns the current record's "status" value
 * @method integer                  getIdUpdate()                       Returns the current record's "id_update" value
 * @method string                   getIpUpdate()                       Returns the current record's "ip_update" value
 * @method string                   getClasificacion()                  Returns the current record's "clasificacion" value
 * @method Rrhh_Configuraciones     getRrhhConfiguraciones()            Returns the current record's "Rrhh_Configuraciones" value
 * @method Funcionarios_Funcionario getFuncionariosFuncionario()        Returns the current record's "Funcionarios_Funcionario" value
 * @method Rrhh_Permisos            setId()                             Sets the current record's "id" value
 * @method Rrhh_Permisos            setConfiguracionesPermisosId()      Sets the current record's "configuraciones_permisos_id" value
 * @method Rrhh_Permisos            setFuncionarioId()                  Sets the current record's "funcionario_id" value
 * @method Rrhh_Permisos            setCorrespondenciaSolicitudId()     Sets the current record's "correspondencia_solicitud_id" value
 * @method Rrhh_Permisos            setTipoPermiso()                    Sets the current record's "tipo_permiso" value
 * @method Rrhh_Permisos            setFInicioPermiso()                 Sets the current record's "f_inicio_permiso" value
 * @method Rrhh_Permisos            setFFinPermiso()                    Sets the current record's "f_fin_permiso" value
 * @method Rrhh_Permisos            setFRetornoPermiso()                Sets the current record's "f_retorno_permiso" value
 * @method Rrhh_Permisos            setDiasSolicitados()                Sets the current record's "dias_solicitados" value
 * @method Rrhh_Permisos            setDiasPermisoHabiles()             Sets the current record's "dias_permiso_habiles" value
 * @method Rrhh_Permisos            setDiasPermisoFinSemana()           Sets the current record's "dias_permiso_fin_semana" value
 * @method Rrhh_Permisos            setDiasPermisoNoLaborales()         Sets the current record's "dias_permiso_no_laborales" value
 * @method Rrhh_Permisos            setDiasPermisoContinuo()            Sets the current record's "dias_permiso_continuo" value
 * @method Rrhh_Permisos            setObservacionesDescritas()         Sets the current record's "observaciones_descritas" value
 * @method Rrhh_Permisos            setObservacionesAutomaticas()       Sets the current record's "observaciones_automaticas" value
 * @method Rrhh_Permisos            setCorrespondenciaCancelacionId()   Sets the current record's "correspondencia_cancelacion_id" value
 * @method Rrhh_Permisos            setMotivoCancelacion()              Sets the current record's "motivo_cancelacion" value
 * @method Rrhh_Permisos            setDiasPermisoEjecutados()          Sets the current record's "dias_permiso_ejecutados" value
 * @method Rrhh_Permisos            setStatus()                         Sets the current record's "status" value
 * @method Rrhh_Permisos            setIdUpdate()                       Sets the current record's "id_update" value
 * @method Rrhh_Permisos            setIpUpdate()                       Sets the current record's "ip_update" value
 * @method Rrhh_Permisos            setClasificacion()                  Sets the current record's "clasificacion" value
 * @method Rrhh_Permisos            setRrhhConfiguraciones()            Sets the current record's "Rrhh_Configuraciones" value
 * @method Rrhh_Permisos            setFuncionariosFuncionario()        Sets the current record's "Funcionarios_Funcionario" value
 * 
 * @package    siglas
 * @subpackage model
 * @author     Livio Lopez
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRrhh_Permisos extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rrhh.permisos');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'rrhh.permisos_id',
             'length' => 4,
             ));
        $this->hasColumn('configuraciones_permisos_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('funcionario_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('correspondencia_solicitud_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('tipo_permiso', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('f_inicio_permiso', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('f_fin_permiso', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('f_retorno_permiso', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('dias_solicitados', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('dias_permiso_habiles', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('dias_permiso_fin_semana', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('dias_permiso_no_laborales', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('dias_permiso_continuo', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('observaciones_descritas', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('observaciones_automaticas', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('correspondencia_cancelacion_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('motivo_cancelacion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('dias_permiso_ejecutados', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('status', 'string', 1, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('id_update', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('ip_update', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 50,
             ));
        $this->hasColumn('clasificacion', 'string', 1, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Rrhh_Configuraciones', array(
             'local' => 'configuraciones_permisos_id',
             'foreign' => 'id'));

        $this->hasOne('Funcionarios_Funcionario', array(
             'local' => 'funcionario_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}