<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Archivo_EstanteModelo', 'doctrine');

/**
 * BaseArchivo_EstanteModelo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property integer $id_update
 * @property Doctrine_Collection $Archivo_Estante
 * 
 * @method integer               getId()              Returns the current record's "id" value
 * @method string                getNombre()          Returns the current record's "nombre" value
 * @method integer               getIdUpdate()        Returns the current record's "id_update" value
 * @method Doctrine_Collection   getArchivoEstante()  Returns the current record's "Archivo_Estante" collection
 * @method Archivo_EstanteModelo setId()              Sets the current record's "id" value
 * @method Archivo_EstanteModelo setNombre()          Sets the current record's "nombre" value
 * @method Archivo_EstanteModelo setIdUpdate()        Sets the current record's "id_update" value
 * @method Archivo_EstanteModelo setArchivoEstante()  Sets the current record's "Archivo_Estante" collection
 * 
 * @package    siglas
 * @subpackage model
 * @author     Livio Lopez
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArchivo_EstanteModelo extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('archivo.estante_modelo');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'archivo.estante_modelo_id',
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('id_update', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Archivo_Estante', array(
             'local' => 'id',
             'foreign' => 'estante_modelo_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}