<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Archivo_Expediente', 'doctrine');

/**
 * BaseArchivo_Expediente
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $padre_id
 * @property string $correlativo
 * @property integer $unidad_id
 * @property integer $expediente_modelo_id
 * @property integer $unidad_correlativos_id
 * @property integer $estante_id
 * @property integer $tramo
 * @property integer $caja_id
 * @property integer $serie_documental_id
 * @property integer $porcentaje_ocupado
 * @property string $status
 * @property integer $id_update
 * @property string $ip_update
 * @property Archivo_Estante $Archivo_Estante
 * @property Archivo_Caja $Archivo_Caja
 * @property Archivo_Expediente $Archivo_Expediente
 * @property Archivo_UnidadCorrelativos $Archivo_UnidadCorrelativos
 * @property Archivo_SerieDocumental $Archivo_SerieDocumental
 * @property Organigrama_Unidad $Organigrama_Unidad
 * @property Archivo_ExpedienteModelo $Archivo_ExpedienteModelo
 * @property Doctrine_Collection $Archivo_ExpedientePadre
 * @property Doctrine_Collection $Archivo_Documento
 * @property Doctrine_Collection $Archivo_ExpedienteClasificador
 * @property Doctrine_Collection $Archivo_PrestamoArchivo
 * @property Doctrine_Collection $Archivo_ExpedienteCuerpoDocumental
 * 
 * @method integer                    getId()                                 Returns the current record's "id" value
 * @method integer                    getPadreId()                            Returns the current record's "padre_id" value
 * @method string                     getCorrelativo()                        Returns the current record's "correlativo" value
 * @method integer                    getUnidadId()                           Returns the current record's "unidad_id" value
 * @method integer                    getExpedienteModeloId()                 Returns the current record's "expediente_modelo_id" value
 * @method integer                    getUnidadCorrelativosId()               Returns the current record's "unidad_correlativos_id" value
 * @method integer                    getEstanteId()                          Returns the current record's "estante_id" value
 * @method integer                    getTramo()                              Returns the current record's "tramo" value
 * @method integer                    getCajaId()                             Returns the current record's "caja_id" value
 * @method integer                    getSerieDocumentalId()                  Returns the current record's "serie_documental_id" value
 * @method integer                    getPorcentajeOcupado()                  Returns the current record's "porcentaje_ocupado" value
 * @method string                     getStatus()                             Returns the current record's "status" value
 * @method integer                    getIdUpdate()                           Returns the current record's "id_update" value
 * @method string                     getIpUpdate()                           Returns the current record's "ip_update" value
 * @method Archivo_Estante            getArchivoEstante()                     Returns the current record's "Archivo_Estante" value
 * @method Archivo_Caja               getArchivoCaja()                        Returns the current record's "Archivo_Caja" value
 * @method Archivo_Expediente         getArchivoExpediente()                  Returns the current record's "Archivo_Expediente" value
 * @method Archivo_UnidadCorrelativos getArchivoUnidadCorrelativos()          Returns the current record's "Archivo_UnidadCorrelativos" value
 * @method Archivo_SerieDocumental    getArchivoSerieDocumental()             Returns the current record's "Archivo_SerieDocumental" value
 * @method Organigrama_Unidad         getOrganigramaUnidad()                  Returns the current record's "Organigrama_Unidad" value
 * @method Archivo_ExpedienteModelo   getArchivoExpedienteModelo()            Returns the current record's "Archivo_ExpedienteModelo" value
 * @method Doctrine_Collection        getArchivoExpedientePadre()             Returns the current record's "Archivo_ExpedientePadre" collection
 * @method Doctrine_Collection        getArchivoDocumento()                   Returns the current record's "Archivo_Documento" collection
 * @method Doctrine_Collection        getArchivoExpedienteClasificador()      Returns the current record's "Archivo_ExpedienteClasificador" collection
 * @method Doctrine_Collection        getArchivoPrestamoArchivo()             Returns the current record's "Archivo_PrestamoArchivo" collection
 * @method Doctrine_Collection        getArchivoExpedienteCuerpoDocumental()  Returns the current record's "Archivo_ExpedienteCuerpoDocumental" collection
 * @method Archivo_Expediente         setId()                                 Sets the current record's "id" value
 * @method Archivo_Expediente         setPadreId()                            Sets the current record's "padre_id" value
 * @method Archivo_Expediente         setCorrelativo()                        Sets the current record's "correlativo" value
 * @method Archivo_Expediente         setUnidadId()                           Sets the current record's "unidad_id" value
 * @method Archivo_Expediente         setExpedienteModeloId()                 Sets the current record's "expediente_modelo_id" value
 * @method Archivo_Expediente         setUnidadCorrelativosId()               Sets the current record's "unidad_correlativos_id" value
 * @method Archivo_Expediente         setEstanteId()                          Sets the current record's "estante_id" value
 * @method Archivo_Expediente         setTramo()                              Sets the current record's "tramo" value
 * @method Archivo_Expediente         setCajaId()                             Sets the current record's "caja_id" value
 * @method Archivo_Expediente         setSerieDocumentalId()                  Sets the current record's "serie_documental_id" value
 * @method Archivo_Expediente         setPorcentajeOcupado()                  Sets the current record's "porcentaje_ocupado" value
 * @method Archivo_Expediente         setStatus()                             Sets the current record's "status" value
 * @method Archivo_Expediente         setIdUpdate()                           Sets the current record's "id_update" value
 * @method Archivo_Expediente         setIpUpdate()                           Sets the current record's "ip_update" value
 * @method Archivo_Expediente         setArchivoEstante()                     Sets the current record's "Archivo_Estante" value
 * @method Archivo_Expediente         setArchivoCaja()                        Sets the current record's "Archivo_Caja" value
 * @method Archivo_Expediente         setArchivoExpediente()                  Sets the current record's "Archivo_Expediente" value
 * @method Archivo_Expediente         setArchivoUnidadCorrelativos()          Sets the current record's "Archivo_UnidadCorrelativos" value
 * @method Archivo_Expediente         setArchivoSerieDocumental()             Sets the current record's "Archivo_SerieDocumental" value
 * @method Archivo_Expediente         setOrganigramaUnidad()                  Sets the current record's "Organigrama_Unidad" value
 * @method Archivo_Expediente         setArchivoExpedienteModelo()            Sets the current record's "Archivo_ExpedienteModelo" value
 * @method Archivo_Expediente         setArchivoExpedientePadre()             Sets the current record's "Archivo_ExpedientePadre" collection
 * @method Archivo_Expediente         setArchivoDocumento()                   Sets the current record's "Archivo_Documento" collection
 * @method Archivo_Expediente         setArchivoExpedienteClasificador()      Sets the current record's "Archivo_ExpedienteClasificador" collection
 * @method Archivo_Expediente         setArchivoPrestamoArchivo()             Sets the current record's "Archivo_PrestamoArchivo" collection
 * @method Archivo_Expediente         setArchivoExpedienteCuerpoDocumental()  Sets the current record's "Archivo_ExpedienteCuerpoDocumental" collection
 * 
 * @package    siglas
 * @subpackage model
 * @author     Livio Lopez
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArchivo_Expediente extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('archivo.expediente');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'archivo.expediente_id',
             'length' => 4,
             ));
        $this->hasColumn('padre_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('correlativo', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('unidad_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('expediente_modelo_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('unidad_correlativos_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('estante_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('tramo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('caja_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('serie_documental_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('porcentaje_ocupado', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('status', 'string', 1, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('id_update', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('ip_update', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Archivo_Estante', array(
             'local' => 'estante_id',
             'foreign' => 'id'));

        $this->hasOne('Archivo_Caja', array(
             'local' => 'caja_id',
             'foreign' => 'id'));

        $this->hasOne('Archivo_Expediente', array(
             'local' => 'padre_id',
             'foreign' => 'id'));

        $this->hasOne('Archivo_UnidadCorrelativos', array(
             'local' => 'unidad_correlativos_id',
             'foreign' => 'id'));

        $this->hasOne('Archivo_SerieDocumental', array(
             'local' => 'serie_documental_id',
             'foreign' => 'id'));

        $this->hasOne('Organigrama_Unidad', array(
             'local' => 'unidad_id',
             'foreign' => 'id'));

        $this->hasOne('Archivo_ExpedienteModelo', array(
             'local' => 'expediente_modelo_id',
             'foreign' => 'id'));

        $this->hasMany('Archivo_Expediente as Archivo_ExpedientePadre', array(
             'local' => 'id',
             'foreign' => 'padre_id'));

        $this->hasMany('Archivo_Documento', array(
             'local' => 'id',
             'foreign' => 'expediente_id'));

        $this->hasMany('Archivo_ExpedienteClasificador', array(
             'local' => 'id',
             'foreign' => 'expediente_id'));

        $this->hasMany('Archivo_PrestamoArchivo', array(
             'local' => 'id',
             'foreign' => 'expediente_id'));

        $this->hasMany('Archivo_ExpedienteCuerpoDocumental', array(
             'local' => 'id',
             'foreign' => 'expediente_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}