<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Archivo_SerieDocumental', 'doctrine');

/**
 * BaseArchivo_SerieDocumental
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $unidad_id
 * @property string $nombre
 * @property string $status
 * @property integer $id_update
 * @property Organigrama_Unidad $Organigrama_Unidad
 * @property Doctrine_Collection $Archivo_Expediente
 * @property Doctrine_Collection $Archivo_CuerpoDocumental
 * @property Doctrine_Collection $Archivo_Clasificador
 * @property Doctrine_Collection $Archivo_TipologiaDocumental
 * @property Doctrine_Collection $Archivo_Almacenamiento
 * 
 * @method integer                 getId()                          Returns the current record's "id" value
 * @method integer                 getUnidadId()                    Returns the current record's "unidad_id" value
 * @method string                  getNombre()                      Returns the current record's "nombre" value
 * @method string                  getStatus()                      Returns the current record's "status" value
 * @method integer                 getIdUpdate()                    Returns the current record's "id_update" value
 * @method Organigrama_Unidad      getOrganigramaUnidad()           Returns the current record's "Organigrama_Unidad" value
 * @method Doctrine_Collection     getArchivoExpediente()           Returns the current record's "Archivo_Expediente" collection
 * @method Doctrine_Collection     getArchivoCuerpoDocumental()     Returns the current record's "Archivo_CuerpoDocumental" collection
 * @method Doctrine_Collection     getArchivoClasificador()         Returns the current record's "Archivo_Clasificador" collection
 * @method Doctrine_Collection     getArchivoTipologiaDocumental()  Returns the current record's "Archivo_TipologiaDocumental" collection
 * @method Doctrine_Collection     getArchivoAlmacenamiento()       Returns the current record's "Archivo_Almacenamiento" collection
 * @method Archivo_SerieDocumental setId()                          Sets the current record's "id" value
 * @method Archivo_SerieDocumental setUnidadId()                    Sets the current record's "unidad_id" value
 * @method Archivo_SerieDocumental setNombre()                      Sets the current record's "nombre" value
 * @method Archivo_SerieDocumental setStatus()                      Sets the current record's "status" value
 * @method Archivo_SerieDocumental setIdUpdate()                    Sets the current record's "id_update" value
 * @method Archivo_SerieDocumental setOrganigramaUnidad()           Sets the current record's "Organigrama_Unidad" value
 * @method Archivo_SerieDocumental setArchivoExpediente()           Sets the current record's "Archivo_Expediente" collection
 * @method Archivo_SerieDocumental setArchivoCuerpoDocumental()     Sets the current record's "Archivo_CuerpoDocumental" collection
 * @method Archivo_SerieDocumental setArchivoClasificador()         Sets the current record's "Archivo_Clasificador" collection
 * @method Archivo_SerieDocumental setArchivoTipologiaDocumental()  Sets the current record's "Archivo_TipologiaDocumental" collection
 * @method Archivo_SerieDocumental setArchivoAlmacenamiento()       Sets the current record's "Archivo_Almacenamiento" collection
 * 
 * @package    siglas
 * @subpackage model
 * @author     Livio Lopez
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArchivo_SerieDocumental extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('archivo.serie_documental');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'archivo.serie_documental_id',
             'length' => 4,
             ));
        $this->hasColumn('unidad_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('status', 'string', 1, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('id_update', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Organigrama_Unidad', array(
             'local' => 'unidad_id',
             'foreign' => 'id'));

        $this->hasMany('Archivo_Expediente', array(
             'local' => 'id',
             'foreign' => 'serie_documental_id'));

        $this->hasMany('Archivo_CuerpoDocumental', array(
             'local' => 'id',
             'foreign' => 'serie_documental_id'));

        $this->hasMany('Archivo_Clasificador', array(
             'local' => 'id',
             'foreign' => 'serie_documental_id'));

        $this->hasMany('Archivo_TipologiaDocumental', array(
             'local' => 'id',
             'foreign' => 'serie_documental_id'));

        $this->hasMany('Archivo_Almacenamiento', array(
             'local' => 'id',
             'foreign' => 'serie_documental_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}