<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Archivo_PrestamoArchivo', 'doctrine');

/**
 * BaseArchivo_PrestamoArchivo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $correspondencia_solicitud_id
 * @property integer $unidad_id
 * @property integer $funcionario_id
 * @property integer $expediente_id
 * @property string $documentos_ids
 * @property date $f_expiracion
 * @property timestamp $f_entrega_fisico
 * @property integer $receptor_entrega_fisico_id
 * @property string $codigo_prestamo_fisico
 * @property boolean $reentrega_fisico
 * @property timestamp $f_devolucion_fisico
 * @property integer $receptor_devolucion_fisico_id
 * @property boolean $digital
 * @property boolean $fisico
 * @property string $status
 * @property integer $id_update
 * @property string $ip_update
 * @property Archivo_Expediente $Archivo_Expediente
 * @property Organigrama_Unidad $Organigrama_Unidad
 * @property Funcionarios_Funcionario $Funcionarios_Funcionario
 * @property Funcionarios_Funcionario $Funcionarios_FuncionarioReceptorEntregaFisico
 * @property Funcionarios_Funcionario $Funcionarios_FuncionarioReceptorDevolucionFisico
 * 
 * @method integer                  getId()                                               Returns the current record's "id" value
 * @method integer                  getCorrespondenciaSolicitudId()                       Returns the current record's "correspondencia_solicitud_id" value
 * @method integer                  getUnidadId()                                         Returns the current record's "unidad_id" value
 * @method integer                  getFuncionarioId()                                    Returns the current record's "funcionario_id" value
 * @method integer                  getExpedienteId()                                     Returns the current record's "expediente_id" value
 * @method string                   getDocumentosIds()                                    Returns the current record's "documentos_ids" value
 * @method date                     getFExpiracion()                                      Returns the current record's "f_expiracion" value
 * @method timestamp                getFEntregaFisico()                                   Returns the current record's "f_entrega_fisico" value
 * @method integer                  getReceptorEntregaFisicoId()                          Returns the current record's "receptor_entrega_fisico_id" value
 * @method string                   getCodigoPrestamoFisico()                             Returns the current record's "codigo_prestamo_fisico" value
 * @method boolean                  getReentregaFisico()                                  Returns the current record's "reentrega_fisico" value
 * @method timestamp                getFDevolucionFisico()                                Returns the current record's "f_devolucion_fisico" value
 * @method integer                  getReceptorDevolucionFisicoId()                       Returns the current record's "receptor_devolucion_fisico_id" value
 * @method boolean                  getDigital()                                          Returns the current record's "digital" value
 * @method boolean                  getFisico()                                           Returns the current record's "fisico" value
 * @method string                   getStatus()                                           Returns the current record's "status" value
 * @method integer                  getIdUpdate()                                         Returns the current record's "id_update" value
 * @method string                   getIpUpdate()                                         Returns the current record's "ip_update" value
 * @method Archivo_Expediente       getArchivoExpediente()                                Returns the current record's "Archivo_Expediente" value
 * @method Organigrama_Unidad       getOrganigramaUnidad()                                Returns the current record's "Organigrama_Unidad" value
 * @method Funcionarios_Funcionario getFuncionariosFuncionario()                          Returns the current record's "Funcionarios_Funcionario" value
 * @method Funcionarios_Funcionario getFuncionariosFuncionarioReceptorEntregaFisico()     Returns the current record's "Funcionarios_FuncionarioReceptorEntregaFisico" value
 * @method Funcionarios_Funcionario getFuncionariosFuncionarioReceptorDevolucionFisico()  Returns the current record's "Funcionarios_FuncionarioReceptorDevolucionFisico" value
 * @method Archivo_PrestamoArchivo  setId()                                               Sets the current record's "id" value
 * @method Archivo_PrestamoArchivo  setCorrespondenciaSolicitudId()                       Sets the current record's "correspondencia_solicitud_id" value
 * @method Archivo_PrestamoArchivo  setUnidadId()                                         Sets the current record's "unidad_id" value
 * @method Archivo_PrestamoArchivo  setFuncionarioId()                                    Sets the current record's "funcionario_id" value
 * @method Archivo_PrestamoArchivo  setExpedienteId()                                     Sets the current record's "expediente_id" value
 * @method Archivo_PrestamoArchivo  setDocumentosIds()                                    Sets the current record's "documentos_ids" value
 * @method Archivo_PrestamoArchivo  setFExpiracion()                                      Sets the current record's "f_expiracion" value
 * @method Archivo_PrestamoArchivo  setFEntregaFisico()                                   Sets the current record's "f_entrega_fisico" value
 * @method Archivo_PrestamoArchivo  setReceptorEntregaFisicoId()                          Sets the current record's "receptor_entrega_fisico_id" value
 * @method Archivo_PrestamoArchivo  setCodigoPrestamoFisico()                             Sets the current record's "codigo_prestamo_fisico" value
 * @method Archivo_PrestamoArchivo  setReentregaFisico()                                  Sets the current record's "reentrega_fisico" value
 * @method Archivo_PrestamoArchivo  setFDevolucionFisico()                                Sets the current record's "f_devolucion_fisico" value
 * @method Archivo_PrestamoArchivo  setReceptorDevolucionFisicoId()                       Sets the current record's "receptor_devolucion_fisico_id" value
 * @method Archivo_PrestamoArchivo  setDigital()                                          Sets the current record's "digital" value
 * @method Archivo_PrestamoArchivo  setFisico()                                           Sets the current record's "fisico" value
 * @method Archivo_PrestamoArchivo  setStatus()                                           Sets the current record's "status" value
 * @method Archivo_PrestamoArchivo  setIdUpdate()                                         Sets the current record's "id_update" value
 * @method Archivo_PrestamoArchivo  setIpUpdate()                                         Sets the current record's "ip_update" value
 * @method Archivo_PrestamoArchivo  setArchivoExpediente()                                Sets the current record's "Archivo_Expediente" value
 * @method Archivo_PrestamoArchivo  setOrganigramaUnidad()                                Sets the current record's "Organigrama_Unidad" value
 * @method Archivo_PrestamoArchivo  setFuncionariosFuncionario()                          Sets the current record's "Funcionarios_Funcionario" value
 * @method Archivo_PrestamoArchivo  setFuncionariosFuncionarioReceptorEntregaFisico()     Sets the current record's "Funcionarios_FuncionarioReceptorEntregaFisico" value
 * @method Archivo_PrestamoArchivo  setFuncionariosFuncionarioReceptorDevolucionFisico()  Sets the current record's "Funcionarios_FuncionarioReceptorDevolucionFisico" value
 * 
 * @package    siglas
 * @subpackage model
 * @author     Livio Lopez
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArchivo_PrestamoArchivo extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('archivo.prestamo_archivo');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'archivo.prestamo_archivo_id',
             'length' => 4,
             ));
        $this->hasColumn('correspondencia_solicitud_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('unidad_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('funcionario_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('expediente_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('documentos_ids', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('f_expiracion', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('f_entrega_fisico', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('receptor_entrega_fisico_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('codigo_prestamo_fisico', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('reentrega_fisico', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('f_devolucion_fisico', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('receptor_devolucion_fisico_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('digital', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('fisico', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('status', 'string', 1, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('id_update', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('ip_update', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Archivo_Expediente', array(
             'local' => 'expediente_id',
             'foreign' => 'id'));

        $this->hasOne('Organigrama_Unidad', array(
             'local' => 'unidad_id',
             'foreign' => 'id'));

        $this->hasOne('Funcionarios_Funcionario', array(
             'local' => 'funcionario_id',
             'foreign' => 'id'));

        $this->hasOne('Funcionarios_Funcionario as Funcionarios_FuncionarioReceptorEntregaFisico', array(
             'local' => 'receptor_entrega_fisico_id',
             'foreign' => 'id'));

        $this->hasOne('Funcionarios_Funcionario as Funcionarios_FuncionarioReceptorDevolucionFisico', array(
             'local' => 'receptor_devolucion_fisico_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}