<?php
// auto-generated by sfSecurityConfigHandler
// date: 2016/05/19 00:00:20
$this->security = array (
  'index' => 
  array (
    'is_secure' => false,
  ),
  'login' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
