<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Seguridad_Preingreso', 'doctrine');

/**
 * BaseSeguridad_Preingreso
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $unidad_id
 * @property integer $funcionario_id
 * @property timestamp $f_ingreso_posible_inicio
 * @property timestamp $f_ingreso_posible_final
 * @property integer $motivo_id
 * @property string $motivo_visita
 * @property string $status
 * @property integer $id_create
 * @property integer $id_update
 * @property string $ip_update
 * @property string $indices
 * @property Organigrama_Unidad $Organigrama_Unidad
 * @property Funcionarios_Funcionario $Funcionarios_Funcionario
 * @property Seguridad_Motivo $Seguridad_Motivo
 * @property Doctrine_Collection $Seguridad_Ingreso
 * 
 * @method integer                  getId()                       Returns the current record's "id" value
 * @method integer                  getUnidadId()                 Returns the current record's "unidad_id" value
 * @method integer                  getFuncionarioId()            Returns the current record's "funcionario_id" value
 * @method timestamp                getFIngresoPosibleInicio()    Returns the current record's "f_ingreso_posible_inicio" value
 * @method timestamp                getFIngresoPosibleFinal()     Returns the current record's "f_ingreso_posible_final" value
 * @method integer                  getMotivoId()                 Returns the current record's "motivo_id" value
 * @method string                   getMotivoVisita()             Returns the current record's "motivo_visita" value
 * @method string                   getStatus()                   Returns the current record's "status" value
 * @method integer                  getIdCreate()                 Returns the current record's "id_create" value
 * @method integer                  getIdUpdate()                 Returns the current record's "id_update" value
 * @method string                   getIpUpdate()                 Returns the current record's "ip_update" value
 * @method string                   getIndices()                  Returns the current record's "indices" value
 * @method Organigrama_Unidad       getOrganigramaUnidad()        Returns the current record's "Organigrama_Unidad" value
 * @method Funcionarios_Funcionario getFuncionariosFuncionario()  Returns the current record's "Funcionarios_Funcionario" value
 * @method Seguridad_Motivo         getSeguridadMotivo()          Returns the current record's "Seguridad_Motivo" value
 * @method Doctrine_Collection      getSeguridadIngreso()         Returns the current record's "Seguridad_Ingreso" collection
 * @method Seguridad_Preingreso     setId()                       Sets the current record's "id" value
 * @method Seguridad_Preingreso     setUnidadId()                 Sets the current record's "unidad_id" value
 * @method Seguridad_Preingreso     setFuncionarioId()            Sets the current record's "funcionario_id" value
 * @method Seguridad_Preingreso     setFIngresoPosibleInicio()    Sets the current record's "f_ingreso_posible_inicio" value
 * @method Seguridad_Preingreso     setFIngresoPosibleFinal()     Sets the current record's "f_ingreso_posible_final" value
 * @method Seguridad_Preingreso     setMotivoId()                 Sets the current record's "motivo_id" value
 * @method Seguridad_Preingreso     setMotivoVisita()             Sets the current record's "motivo_visita" value
 * @method Seguridad_Preingreso     setStatus()                   Sets the current record's "status" value
 * @method Seguridad_Preingreso     setIdCreate()                 Sets the current record's "id_create" value
 * @method Seguridad_Preingreso     setIdUpdate()                 Sets the current record's "id_update" value
 * @method Seguridad_Preingreso     setIpUpdate()                 Sets the current record's "ip_update" value
 * @method Seguridad_Preingreso     setIndices()                  Sets the current record's "indices" value
 * @method Seguridad_Preingreso     setOrganigramaUnidad()        Sets the current record's "Organigrama_Unidad" value
 * @method Seguridad_Preingreso     setFuncionariosFuncionario()  Sets the current record's "Funcionarios_Funcionario" value
 * @method Seguridad_Preingreso     setSeguridadMotivo()          Sets the current record's "Seguridad_Motivo" value
 * @method Seguridad_Preingreso     setSeguridadIngreso()         Sets the current record's "Seguridad_Ingreso" collection
 * 
 * @package    siglas
 * @subpackage model
 * @author     Livio Lopez
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSeguridad_Preingreso extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('seguridad.preingreso');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'seguridad.preingreso_id',
             'length' => 4,
             ));
        $this->hasColumn('unidad_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('funcionario_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('f_ingreso_posible_inicio', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('f_ingreso_posible_final', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('motivo_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('motivo_visita', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('status', 'string', 1, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('id_create', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_update', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('ip_update', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 50,
             ));
        $this->hasColumn('indices', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Organigrama_Unidad', array(
             'local' => 'unidad_id',
             'foreign' => 'id'));

        $this->hasOne('Funcionarios_Funcionario', array(
             'local' => 'funcionario_id',
             'foreign' => 'id'));

        $this->hasOne('Seguridad_Motivo', array(
             'local' => 'motivo_id',
             'foreign' => 'id'));

        $this->hasMany('Seguridad_Ingreso', array(
             'local' => 'id',
             'foreign' => 'preingreso_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}