<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Seguridad_Equipo', 'doctrine');

/**
 * BaseSeguridad_Equipo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $tipo_id
 * @property integer $marca_id
 * @property string $serial
 * @property integer $id_update
 * @property string $ip_update
 * @property Seguridad_Tipo $Seguridad_Tipo
 * @property Seguridad_Marca $Seguridad_Marca
 * @property Doctrine_Collection $Seguridad_IngresoEquipo
 * 
 * @method integer             getId()                      Returns the current record's "id" value
 * @method integer             getTipoId()                  Returns the current record's "tipo_id" value
 * @method integer             getMarcaId()                 Returns the current record's "marca_id" value
 * @method string              getSerial()                  Returns the current record's "serial" value
 * @method integer             getIdUpdate()                Returns the current record's "id_update" value
 * @method string              getIpUpdate()                Returns the current record's "ip_update" value
 * @method Seguridad_Tipo      getSeguridadTipo()           Returns the current record's "Seguridad_Tipo" value
 * @method Seguridad_Marca     getSeguridadMarca()          Returns the current record's "Seguridad_Marca" value
 * @method Doctrine_Collection getSeguridadIngresoEquipo()  Returns the current record's "Seguridad_IngresoEquipo" collection
 * @method Seguridad_Equipo    setId()                      Sets the current record's "id" value
 * @method Seguridad_Equipo    setTipoId()                  Sets the current record's "tipo_id" value
 * @method Seguridad_Equipo    setMarcaId()                 Sets the current record's "marca_id" value
 * @method Seguridad_Equipo    setSerial()                  Sets the current record's "serial" value
 * @method Seguridad_Equipo    setIdUpdate()                Sets the current record's "id_update" value
 * @method Seguridad_Equipo    setIpUpdate()                Sets the current record's "ip_update" value
 * @method Seguridad_Equipo    setSeguridadTipo()           Sets the current record's "Seguridad_Tipo" value
 * @method Seguridad_Equipo    setSeguridadMarca()          Sets the current record's "Seguridad_Marca" value
 * @method Seguridad_Equipo    setSeguridadIngresoEquipo()  Sets the current record's "Seguridad_IngresoEquipo" collection
 * 
 * @package    siglas
 * @subpackage model
 * @author     Livio Lopez
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSeguridad_Equipo extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('seguridad.equipo');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'seguridad.equipo_id',
             'length' => 4,
             ));
        $this->hasColumn('tipo_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('marca_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('serial', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('id_update', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('ip_update', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Seguridad_Tipo', array(
             'local' => 'tipo_id',
             'foreign' => 'id'));

        $this->hasOne('Seguridad_Marca', array(
             'local' => 'marca_id',
             'foreign' => 'id'));

        $this->hasMany('Seguridad_IngresoEquipo', array(
             'local' => 'id',
             'foreign' => 'equipo_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}