<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Comunicaciones_Metodo', 'doctrine');

/**
 * BaseComunicaciones_Metodo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property string $descripcion
 * @property string $status
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property integer $id_update
 * @property string $ip_update
 * @property Doctrine_Collection $Comunicaciones_Notificacions
 * @property Doctrine_Collection $Comunicaciones_NotificacionHistorico
 * 
 * @method integer               getId()                                   Returns the current record's "id" value
 * @method string                getNombre()                               Returns the current record's "nombre" value
 * @method string                getDescripcion()                          Returns the current record's "descripcion" value
 * @method string                getStatus()                               Returns the current record's "status" value
 * @method timestamp             getCreatedAt()                            Returns the current record's "created_at" value
 * @method timestamp             getUpdatedAt()                            Returns the current record's "updated_at" value
 * @method integer               getIdUpdate()                             Returns the current record's "id_update" value
 * @method string                getIpUpdate()                             Returns the current record's "ip_update" value
 * @method Doctrine_Collection   getComunicacionesNotificacions()          Returns the current record's "Comunicaciones_Notificacions" collection
 * @method Doctrine_Collection   getComunicacionesNotificacionHistorico()  Returns the current record's "Comunicaciones_NotificacionHistorico" collection
 * @method Comunicaciones_Metodo setId()                                   Sets the current record's "id" value
 * @method Comunicaciones_Metodo setNombre()                               Sets the current record's "nombre" value
 * @method Comunicaciones_Metodo setDescripcion()                          Sets the current record's "descripcion" value
 * @method Comunicaciones_Metodo setStatus()                               Sets the current record's "status" value
 * @method Comunicaciones_Metodo setCreatedAt()                            Sets the current record's "created_at" value
 * @method Comunicaciones_Metodo setUpdatedAt()                            Sets the current record's "updated_at" value
 * @method Comunicaciones_Metodo setIdUpdate()                             Sets the current record's "id_update" value
 * @method Comunicaciones_Metodo setIpUpdate()                             Sets the current record's "ip_update" value
 * @method Comunicaciones_Metodo setComunicacionesNotificacions()          Sets the current record's "Comunicaciones_Notificacions" collection
 * @method Comunicaciones_Metodo setComunicacionesNotificacionHistorico()  Sets the current record's "Comunicaciones_NotificacionHistorico" collection
 * 
 * @package    siglas
 * @subpackage model
 * @author     Livio Lopez
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComunicaciones_Metodo extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comunicaciones.metodo');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'comunicaciones.metodo_id',
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 150,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('status', 'string', 1, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('id_update', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('ip_update', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 30,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Comunicaciones_Notificacion as Comunicaciones_Notificacions', array(
             'local' => 'id',
             'foreign' => 'metodo_id'));

        $this->hasMany('Comunicaciones_NotificacionHistorico', array(
             'local' => 'id',
             'foreign' => 'metodo_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}