<?php

/**
 * Archivo_Estante
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    siglas
 * @subpackage model
 * @author     Livio Lopez
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Archivo_Estante extends BaseArchivo_Estante
{
    public function __toString()
    {
        return $this->getIdentificador();
    }
    
    public function save(Doctrine_Connection $conn = null)
    {           
        if($this->isNew()) {
            $this->setPorcentajeOcupado(0);
        }
        
        // ############ OJO CAMBIAR ESTO POR LA UNIDAD DUEÑA DE LA SERIE DOCUMENTAL
//        if(!$this->getUnidadDuenaId())
//            $this->setUnidadDuenaId(sfContext::getInstance()->getUser()->getAttribute('funcionario_unidad_id'));

        return parent::save($conn);
    }   
}
