<?php

/**
 * Archivo_CuerpoDocumental
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    siglas
 * @subpackage model
 * @author     Livio Lopez
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Archivo_CuerpoDocumental extends BaseArchivo_CuerpoDocumental
{
    public function save(Doctrine_Connection $conn = null)
    {           
        if($this->isNew()) {
            if(sfContext::getInstance()->getUser()->hasAttribute('serie_documental_id')) {
                $this->setSerieDocumentalId(sfContext::getInstance()->getUser()->getAttribute('serie_documental_id'));
            }
        }

        return parent::save($conn);
    }
    
  public function postSave($event)
  {
    $cacheDriver = $this->getTable()->getAttribute(Doctrine_Core::ATTR_RESULT_CACHE);
    $cacheDriver->deleteByPrefix('cache_cuerpo_documental_');
  }

  public function postDelete($event)
  {
    $cacheDriver = $this->getTable()->getAttribute(Doctrine_Core::ATTR_RESULT_CACHE);
    $cacheDriver->deleteByPrefix('cache_cuerpo_documental_');
  }
}
