<?php

/**
 * Archivo_SerieDocumental
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    siglas
 * @subpackage model
 * @author     Livio Lopez
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Archivo_SerieDocumental extends BaseArchivo_SerieDocumental
{
//    public function save(Doctrine_Connection $conn = null)
//    {           
//        if($this->isNew()) {
//            $this->setUnidadId(sfContext::getInstance()->getUser()->getAttribute('funcionario_unidad_id'));
//        }
//
//        return parent::save($conn);
//    }    
}
