generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Inventario_ArticuloEgreso
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          inventario_articulo_egreso
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        table_method: innerListDespachoArticulos
        title: Despacho de articulo 
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
