<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Correspondencia_TipoFormato', 'doctrine');

/**
 * BaseCorrespondencia_TipoFormato
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property string $descripcion
 * @property string $privado
 * @property boolean $principal
 * @property string $tipo
 * @property string $classe
 * @property string $parametros
 * @property integer $id_update
 * @property string $status
 * @property Doctrine_Collection $Correspondencia_Formato
 * @property Doctrine_Collection $Correspondencia_VistobuenoGeneralConfig
 * @property Doctrine_Collection $Correspondencia_CorrelativosFormatos
 * 
 * @method integer                     getId()                                      Returns the current record's "id" value
 * @method string                      getNombre()                                  Returns the current record's "nombre" value
 * @method string                      getDescripcion()                             Returns the current record's "descripcion" value
 * @method string                      getPrivado()                                 Returns the current record's "privado" value
 * @method boolean                     getPrincipal()                               Returns the current record's "principal" value
 * @method string                      getTipo()                                    Returns the current record's "tipo" value
 * @method string                      getClasse()                                  Returns the current record's "classe" value
 * @method string                      getParametros()                              Returns the current record's "parametros" value
 * @method integer                     getIdUpdate()                                Returns the current record's "id_update" value
 * @method string                      getStatus()                                  Returns the current record's "status" value
 * @method Doctrine_Collection         getCorrespondenciaFormato()                  Returns the current record's "Correspondencia_Formato" collection
 * @method Doctrine_Collection         getCorrespondenciaVistobuenoGeneralConfig()  Returns the current record's "Correspondencia_VistobuenoGeneralConfig" collection
 * @method Doctrine_Collection         getCorrespondenciaCorrelativosFormatos()     Returns the current record's "Correspondencia_CorrelativosFormatos" collection
 * @method Correspondencia_TipoFormato setId()                                      Sets the current record's "id" value
 * @method Correspondencia_TipoFormato setNombre()                                  Sets the current record's "nombre" value
 * @method Correspondencia_TipoFormato setDescripcion()                             Sets the current record's "descripcion" value
 * @method Correspondencia_TipoFormato setPrivado()                                 Sets the current record's "privado" value
 * @method Correspondencia_TipoFormato setPrincipal()                               Sets the current record's "principal" value
 * @method Correspondencia_TipoFormato setTipo()                                    Sets the current record's "tipo" value
 * @method Correspondencia_TipoFormato setClasse()                                  Sets the current record's "classe" value
 * @method Correspondencia_TipoFormato setParametros()                              Sets the current record's "parametros" value
 * @method Correspondencia_TipoFormato setIdUpdate()                                Sets the current record's "id_update" value
 * @method Correspondencia_TipoFormato setStatus()                                  Sets the current record's "status" value
 * @method Correspondencia_TipoFormato setCorrespondenciaFormato()                  Sets the current record's "Correspondencia_Formato" collection
 * @method Correspondencia_TipoFormato setCorrespondenciaVistobuenoGeneralConfig()  Sets the current record's "Correspondencia_VistobuenoGeneralConfig" collection
 * @method Correspondencia_TipoFormato setCorrespondenciaCorrelativosFormatos()     Sets the current record's "Correspondencia_CorrelativosFormatos" collection
 * 
 * @package    siglas
 * @subpackage model
 * @author     Livio Lopez
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCorrespondencia_TipoFormato extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('correspondencia.tipo_formato');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'correspondencia.tipo_formato_id',
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('privado', 'string', 1, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('principal', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('tipo', 'string', 1, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('classe', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('parametros', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('id_update', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('status', 'string', 1, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Correspondencia_Formato', array(
             'local' => 'id',
             'foreign' => 'tipo_formato_id'));

        $this->hasMany('Correspondencia_VistobuenoGeneralConfig', array(
             'local' => 'id',
             'foreign' => 'tipo_formato_id'));

        $this->hasMany('Correspondencia_CorrelativosFormatos', array(
             'local' => 'id',
             'foreign' => 'tipo_formato_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}