<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Correspondencia_Formato', 'doctrine');

/**
 * BaseCorrespondencia_Formato
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $correspondencia_id
 * @property integer $tipo_formato_id
 * @property string $contenido
 * @property string $campo_uno
 * @property string $campo_dos
 * @property string $campo_tres
 * @property string $campo_cuatro
 * @property string $campo_cinco
 * @property string $campo_seis
 * @property string $campo_siete
 * @property string $campo_ocho
 * @property string $campo_nueve
 * @property string $campo_diez
 * @property string $campo_once
 * @property string $campo_doce
 * @property string $campo_trece
 * @property string $campo_catorce
 * @property string $campo_quince
 * @property integer $id_update
 * @property string $publico
 * @property Correspondencia_Correspondencia $Correspondencia_Correspondencia
 * @property Correspondencia_TipoFormato $Correspondencia_TipoFormato
 * 
 * @method integer                         getId()                              Returns the current record's "id" value
 * @method integer                         getCorrespondenciaId()               Returns the current record's "correspondencia_id" value
 * @method integer                         getTipoFormatoId()                   Returns the current record's "tipo_formato_id" value
 * @method string                          getContenido()                       Returns the current record's "contenido" value
 * @method string                          getCampoUno()                        Returns the current record's "campo_uno" value
 * @method string                          getCampoDos()                        Returns the current record's "campo_dos" value
 * @method string                          getCampoTres()                       Returns the current record's "campo_tres" value
 * @method string                          getCampoCuatro()                     Returns the current record's "campo_cuatro" value
 * @method string                          getCampoCinco()                      Returns the current record's "campo_cinco" value
 * @method string                          getCampoSeis()                       Returns the current record's "campo_seis" value
 * @method string                          getCampoSiete()                      Returns the current record's "campo_siete" value
 * @method string                          getCampoOcho()                       Returns the current record's "campo_ocho" value
 * @method string                          getCampoNueve()                      Returns the current record's "campo_nueve" value
 * @method string                          getCampoDiez()                       Returns the current record's "campo_diez" value
 * @method string                          getCampoOnce()                       Returns the current record's "campo_once" value
 * @method string                          getCampoDoce()                       Returns the current record's "campo_doce" value
 * @method string                          getCampoTrece()                      Returns the current record's "campo_trece" value
 * @method string                          getCampoCatorce()                    Returns the current record's "campo_catorce" value
 * @method string                          getCampoQuince()                     Returns the current record's "campo_quince" value
 * @method integer                         getIdUpdate()                        Returns the current record's "id_update" value
 * @method string                          getPublico()                         Returns the current record's "publico" value
 * @method Correspondencia_Correspondencia getCorrespondenciaCorrespondencia()  Returns the current record's "Correspondencia_Correspondencia" value
 * @method Correspondencia_TipoFormato     getCorrespondenciaTipoFormato()      Returns the current record's "Correspondencia_TipoFormato" value
 * @method Correspondencia_Formato         setId()                              Sets the current record's "id" value
 * @method Correspondencia_Formato         setCorrespondenciaId()               Sets the current record's "correspondencia_id" value
 * @method Correspondencia_Formato         setTipoFormatoId()                   Sets the current record's "tipo_formato_id" value
 * @method Correspondencia_Formato         setContenido()                       Sets the current record's "contenido" value
 * @method Correspondencia_Formato         setCampoUno()                        Sets the current record's "campo_uno" value
 * @method Correspondencia_Formato         setCampoDos()                        Sets the current record's "campo_dos" value
 * @method Correspondencia_Formato         setCampoTres()                       Sets the current record's "campo_tres" value
 * @method Correspondencia_Formato         setCampoCuatro()                     Sets the current record's "campo_cuatro" value
 * @method Correspondencia_Formato         setCampoCinco()                      Sets the current record's "campo_cinco" value
 * @method Correspondencia_Formato         setCampoSeis()                       Sets the current record's "campo_seis" value
 * @method Correspondencia_Formato         setCampoSiete()                      Sets the current record's "campo_siete" value
 * @method Correspondencia_Formato         setCampoOcho()                       Sets the current record's "campo_ocho" value
 * @method Correspondencia_Formato         setCampoNueve()                      Sets the current record's "campo_nueve" value
 * @method Correspondencia_Formato         setCampoDiez()                       Sets the current record's "campo_diez" value
 * @method Correspondencia_Formato         setCampoOnce()                       Sets the current record's "campo_once" value
 * @method Correspondencia_Formato         setCampoDoce()                       Sets the current record's "campo_doce" value
 * @method Correspondencia_Formato         setCampoTrece()                      Sets the current record's "campo_trece" value
 * @method Correspondencia_Formato         setCampoCatorce()                    Sets the current record's "campo_catorce" value
 * @method Correspondencia_Formato         setCampoQuince()                     Sets the current record's "campo_quince" value
 * @method Correspondencia_Formato         setIdUpdate()                        Sets the current record's "id_update" value
 * @method Correspondencia_Formato         setPublico()                         Sets the current record's "publico" value
 * @method Correspondencia_Formato         setCorrespondenciaCorrespondencia()  Sets the current record's "Correspondencia_Correspondencia" value
 * @method Correspondencia_Formato         setCorrespondenciaTipoFormato()      Sets the current record's "Correspondencia_TipoFormato" value
 * 
 * @package    siglas
 * @subpackage model
 * @author     Livio Lopez
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCorrespondencia_Formato extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('correspondencia.formato');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'correspondencia.formato_id',
             'length' => 4,
             ));
        $this->hasColumn('correspondencia_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('tipo_formato_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('contenido', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('campo_uno', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('campo_dos', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('campo_tres', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('campo_cuatro', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('campo_cinco', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('campo_seis', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('campo_siete', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('campo_ocho', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('campo_nueve', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('campo_diez', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('campo_once', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('campo_doce', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('campo_trece', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('campo_catorce', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('campo_quince', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('id_update', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('publico', 'string', 1, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Correspondencia_Correspondencia', array(
             'local' => 'correspondencia_id',
             'foreign' => 'id'));

        $this->hasOne('Correspondencia_TipoFormato', array(
             'local' => 'tipo_formato_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}