<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Correspondencia_Plantilla', 'doctrine');

/**
 * BaseCorrespondencia_Plantilla
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property integer $tipo_formato_id
 * @property string $campo_uno
 * @property string $campo_dos
 * @property string $campo_tres
 * @property string $campo_cuatro
 * @property string $campo_cinco
 * @property string $campo_seis
 * @property string $campo_siete
 * @property string $campo_ocho
 * @property string $campo_nueve
 * @property string $campo_diez
 * @property string $campo_once
 * @property string $campo_doce
 * @property string $campo_trece
 * @property string $campo_catorce
 * @property string $campo_quince
 * @property integer $id_update
 * @property string $ip_update
 * @property Doctrine_Collection $Correspondencia_PlantillaFuncionario
 * 
 * @method integer                   getId()                                   Returns the current record's "id" value
 * @method string                    getNombre()                               Returns the current record's "nombre" value
 * @method integer                   getTipoFormatoId()                        Returns the current record's "tipo_formato_id" value
 * @method string                    getCampoUno()                             Returns the current record's "campo_uno" value
 * @method string                    getCampoDos()                             Returns the current record's "campo_dos" value
 * @method string                    getCampoTres()                            Returns the current record's "campo_tres" value
 * @method string                    getCampoCuatro()                          Returns the current record's "campo_cuatro" value
 * @method string                    getCampoCinco()                           Returns the current record's "campo_cinco" value
 * @method string                    getCampoSeis()                            Returns the current record's "campo_seis" value
 * @method string                    getCampoSiete()                           Returns the current record's "campo_siete" value
 * @method string                    getCampoOcho()                            Returns the current record's "campo_ocho" value
 * @method string                    getCampoNueve()                           Returns the current record's "campo_nueve" value
 * @method string                    getCampoDiez()                            Returns the current record's "campo_diez" value
 * @method string                    getCampoOnce()                            Returns the current record's "campo_once" value
 * @method string                    getCampoDoce()                            Returns the current record's "campo_doce" value
 * @method string                    getCampoTrece()                           Returns the current record's "campo_trece" value
 * @method string                    getCampoCatorce()                         Returns the current record's "campo_catorce" value
 * @method string                    getCampoQuince()                          Returns the current record's "campo_quince" value
 * @method integer                   getIdUpdate()                             Returns the current record's "id_update" value
 * @method string                    getIpUpdate()                             Returns the current record's "ip_update" value
 * @method Doctrine_Collection       getCorrespondenciaPlantillaFuncionario()  Returns the current record's "Correspondencia_PlantillaFuncionario" collection
 * @method Correspondencia_Plantilla setId()                                   Sets the current record's "id" value
 * @method Correspondencia_Plantilla setNombre()                               Sets the current record's "nombre" value
 * @method Correspondencia_Plantilla setTipoFormatoId()                        Sets the current record's "tipo_formato_id" value
 * @method Correspondencia_Plantilla setCampoUno()                             Sets the current record's "campo_uno" value
 * @method Correspondencia_Plantilla setCampoDos()                             Sets the current record's "campo_dos" value
 * @method Correspondencia_Plantilla setCampoTres()                            Sets the current record's "campo_tres" value
 * @method Correspondencia_Plantilla setCampoCuatro()                          Sets the current record's "campo_cuatro" value
 * @method Correspondencia_Plantilla setCampoCinco()                           Sets the current record's "campo_cinco" value
 * @method Correspondencia_Plantilla setCampoSeis()                            Sets the current record's "campo_seis" value
 * @method Correspondencia_Plantilla setCampoSiete()                           Sets the current record's "campo_siete" value
 * @method Correspondencia_Plantilla setCampoOcho()                            Sets the current record's "campo_ocho" value
 * @method Correspondencia_Plantilla setCampoNueve()                           Sets the current record's "campo_nueve" value
 * @method Correspondencia_Plantilla setCampoDiez()                            Sets the current record's "campo_diez" value
 * @method Correspondencia_Plantilla setCampoOnce()                            Sets the current record's "campo_once" value
 * @method Correspondencia_Plantilla setCampoDoce()                            Sets the current record's "campo_doce" value
 * @method Correspondencia_Plantilla setCampoTrece()                           Sets the current record's "campo_trece" value
 * @method Correspondencia_Plantilla setCampoCatorce()                         Sets the current record's "campo_catorce" value
 * @method Correspondencia_Plantilla setCampoQuince()                          Sets the current record's "campo_quince" value
 * @method Correspondencia_Plantilla setIdUpdate()                             Sets the current record's "id_update" value
 * @method Correspondencia_Plantilla setIpUpdate()                             Sets the current record's "ip_update" value
 * @method Correspondencia_Plantilla setCorrespondenciaPlantillaFuncionario()  Sets the current record's "Correspondencia_PlantillaFuncionario" collection
 * 
 * @package    siglas
 * @subpackage model
 * @author     Livio Lopez
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCorrespondencia_Plantilla extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('correspondencia.plantilla');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'correspondencia.plantilla_id',
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('tipo_formato_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('campo_uno', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('campo_dos', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('campo_tres', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('campo_cuatro', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('campo_cinco', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('campo_seis', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('campo_siete', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('campo_ocho', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('campo_nueve', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('campo_diez', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('campo_once', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('campo_doce', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('campo_trece', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('campo_catorce', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('campo_quince', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('id_update', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('ip_update', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Correspondencia_PlantillaFuncionario', array(
             'local' => 'id',
             'foreign' => 'plantilla_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}