generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Organismos_Organismo
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          organismos_organismo
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [nombre, siglas, created_at]
        max_per_page: 200
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
