correspondencia:
  Siglas-Año-Secuencia: true
  Siglas-Año-Mes-Secuencia: true
  Siglas-Año-Mes-Día-Secuencia: true
  Siglas-Letra-Año-Secuencia: true
  Siglas-Letra-Año-Mes-Secuencia: false
  Siglas-Letra-Año-Mes-Día-Secuencia: false
  Siglas-Codigo-Año-Secuencia: true
  Siglas-Codigo-Año-Mes-Secuencia: false
  Siglas-Codigo-Año-Mes-Día-Secuencia: false
  Siglas-Codigo-Letra-Año-Secuencia: true
  Siglas-Codigo-Letra-Año-Mes-Secuencia: false
  Siglas-Codigo-Letra-Año-Mes-Día-Secuencia: false
  Siglas-Año-Secuencia-Letra: true
  Siglas-Año-Mes-Secuencia-Letra: false
  Siglas-Año-Mes-Día-Secuencia-Letra: false
  Siglas-Año-Codigo-Secuencia: true
  Siglas-Año-Mes-Codigo-Secuencia: false
  Siglas-Año-Mes-Día-Codigo-Secuencia: false
  Secuencia-Año-Siglas: true
  Secuencia-Año-Mes-Siglas: false
  Secuencia-Año-Mes-Día-Siglas: false
  Secuencia-Letra-Año-Siglas: true
  Secuencia-Letra-Año-Mes-Siglas: false
  Secuencia-Letra-Año-Mes-Día-Siglas: false
  Secuencia-Año-Siglas-Letra: true
  Secuencia-Año-Mes-Siglas-Letra: false
  Secuencia-Año-Mes-Día-Siglas-Letra: false
  Letra-Siglas-Año-Secuencia: true
  Letra-Siglas-Año-Mes-Secuencia: false
  Letra-Siglas-Año-Mes-Día-Secuencia: false
  Codigo-Año-Secuencia: true
  Codigo-Año-Mes-Secuencia: true
  Codigo-Año-Mes-Día-Secuencia: true
  Codigo-Siglas-Año-Secuencia: true
  Codigo-Siglas-Año-Mes-Secuencia: true
  Codigo-Siglas-Año-Mes-Día-Secuencia: true
  Codigo-Letra-Año-Secuencia: true
  Codigo-Letra-Año-Mes-Secuencia: false
  Codigo-Letra-Año-Mes-Día-Secuencia: true
  Codigo-Siglas-Letra-Año-Secuencia: false
  Codigo-Siglas-Letra-Año-Mes-Secuencia: false
  Codigo-Siglas-Letra-Año-Mes-Día-Secuencia: true
archivo:
  pronto: pronto
