dias_no_laborables:
  '2012-01-01': 'Año Nuevo#t'
  '2012-04-19': 'Declaración de la Independencia#t'
  '2012-05-01': 'Día del trabajador#t'
  '2012-07-05': 'Día de la Independencia#t'
  '2012-07-24': 'Natalicio de Simón Bolívar#t'
  '2012-10-12': 'Día de la resistencia indígena #t'
