<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Proveedores_Proveedor', 'doctrine');

/**
 * BaseProveedores_Proveedor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $tipo_empresa_id
 * @property string $rif
 * @property string $razon_social
 * @property string $status
 * @property integer $id_update
 * @property string $ip_update
 * @property Proveedores_TipoEmpresa $Proveedores_TipoEmpresa
 * @property Doctrine_Collection $Inventario_ArticuloIngreso
 * 
 * @method integer                 getId()                         Returns the current record's "id" value
 * @method integer                 getTipoEmpresaId()              Returns the current record's "tipo_empresa_id" value
 * @method string                  getRif()                        Returns the current record's "rif" value
 * @method string                  getRazonSocial()                Returns the current record's "razon_social" value
 * @method string                  getStatus()                     Returns the current record's "status" value
 * @method integer                 getIdUpdate()                   Returns the current record's "id_update" value
 * @method string                  getIpUpdate()                   Returns the current record's "ip_update" value
 * @method Proveedores_TipoEmpresa getProveedoresTipoEmpresa()     Returns the current record's "Proveedores_TipoEmpresa" value
 * @method Doctrine_Collection     getInventarioArticuloIngreso()  Returns the current record's "Inventario_ArticuloIngreso" collection
 * @method Proveedores_Proveedor   setId()                         Sets the current record's "id" value
 * @method Proveedores_Proveedor   setTipoEmpresaId()              Sets the current record's "tipo_empresa_id" value
 * @method Proveedores_Proveedor   setRif()                        Sets the current record's "rif" value
 * @method Proveedores_Proveedor   setRazonSocial()                Sets the current record's "razon_social" value
 * @method Proveedores_Proveedor   setStatus()                     Sets the current record's "status" value
 * @method Proveedores_Proveedor   setIdUpdate()                   Sets the current record's "id_update" value
 * @method Proveedores_Proveedor   setIpUpdate()                   Sets the current record's "ip_update" value
 * @method Proveedores_Proveedor   setProveedoresTipoEmpresa()     Sets the current record's "Proveedores_TipoEmpresa" value
 * @method Proveedores_Proveedor   setInventarioArticuloIngreso()  Sets the current record's "Inventario_ArticuloIngreso" collection
 * 
 * @package    siglas
 * @subpackage model
 * @author     Livio Lopez
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProveedores_Proveedor extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('proveedores.proveedor');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'proveedores.proveedor_id',
             'length' => 4,
             ));
        $this->hasColumn('tipo_empresa_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('rif', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 50,
             ));
        $this->hasColumn('razon_social', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('status', 'string', 1, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('id_update', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('ip_update', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Proveedores_TipoEmpresa', array(
             'local' => 'tipo_empresa_id',
             'foreign' => 'id'));

        $this->hasMany('Inventario_ArticuloIngreso', array(
             'local' => 'id',
             'foreign' => 'proveedor_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}