organigrama_cargo_condicion:
  class: sfDoctrineRouteCollection
  options:
    model:                Organigrama_CargoCondicion
    module:               cargo_condicion
    prefix_path:          /cargo_condicion
    column:               id
    with_wildcard_routes: true

organigrama_cargo_grado:
  class: sfDoctrineRouteCollection
  options:
    model:                Organigrama_CargoGrado
    module:               cargo_grado
    prefix_path:          /cargo_grado
    column:               id
    with_wildcard_routes: true

organigrama_cargo_tipo:
  class: sfDoctrineRouteCollection
  options:
    model:                Organigrama_CargoTipo
    module:               cargo_tipo
    prefix_path:          /cargo_tipo
    column:               id
    with_wildcard_routes: true

organigrama_cargo:
  class: sfDoctrineRouteCollection
  options:
    model:                Organigrama_Cargo
    module:               cargo
    prefix_path:          /cargo
    column:               id
    with_wildcard_routes: true

organigrama_unidad_tipo:
  class: sfDoctrineRouteCollection
  options:
    model:                Organigrama_UnidadTipo
    module:               unidad_tipo
    prefix_path:          /unidad_tipo
    column:               id
    with_wildcard_routes: true

organigrama_unidad:
  class: sfDoctrineRouteCollection
  options:
    model:                Organigrama_Unidad
    module:               unidad
    prefix_path:          /unidad
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
