generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Archivo_Expediente
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          archivo_expediente_expedientes_compartidos
    with_doctrine_route:   true
    actions_base_class:    sfActions
      
    config:
      actions: ~
      fields: ~
      list:
        table_method: innerListCompartidos
        title: Expedientes Compartidos
        display: [_identificacion_list, _ubicacion, _documentos]
        fields:
          identificacion_list: { label: Identificación }
          ubicacion: { label: Ubicación }
          documentos: {label: Documentos archivados }
        actions:
          excel: {label: Exportar, action: excel}
        object_actions:
          solicitar_fisico: { action: solicitarFisico }
        batch_actions: []
      filter:
        display: [ correlativo, _identificacion_filter, contenido_documento ]
      form:    ~
      edit:  ~
      new:  ~
