<?php

/**
 * Acceso_AutorizacionModulo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    siglas-(institucion)
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Acceso_AutorizacionModulo extends BaseAcceso_AutorizacionModulo
{
    public function save(Doctrine_Connection $conn = null)
    {
        if(sfContext::getInstance()->getUser()->getAttribute('autorizacion')=='punto_cuenta')
            $this->setModuloId(5);
        
        return parent::save($conn);
    }
}
