generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Seguridad_Preingreso
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          seguridad_preingreso
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        f_ingreso_posible_inicio: { label: Desde }
        f_ingreso_posible_final: { label: Hasta }
      list:
        table_method: innerList
        title: Preingreso de Visitantes
        max_per_page:   50
        display: [_visitantes, _destino, _estancia]
        actions:
          _new: []
          regresar_modulo: { label: Regresar, action: regresar }
        object_actions:
          _edit: []
          _delete: []
          ingresar: { label: Registrar ingreso, action: registrarIngreso }
      filter:
        class: false
      form:    ~
      edit:    ~
      new:
        title: Nuevo preingreso
        display:
          Visitantes: [_visitantes_form]
          Destino y motivo: [_destino_form]
          Posible fecha de ingreso: [_estancia_form]
        actions:
          _save: []
