<?php

/**
 * Correspondencia_AnexoArchivo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sigla-(institution)
 * @subpackage model
 * @author     Livio López. liviolopez@gmail.com. (058)426-511.42.50. Venezuela-Caracas
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Correspondencia_AnexoArchivo extends BaseCorrespondencia_AnexoArchivo
{
    public function save(Doctrine_Connection $conn = null)
    {
        if(!$this->get('correspondencia_id'))
            $this->setCorrespondencia_id(sfContext::getInstance()->getUser()->getAttribute('correspondencia_id'));
        
//        if(sfContext::getInstance()->getUser()->getAttribute('c_tipo_archivo'))
//            $this->setTipoAnexoArchivo(sfContext::getInstance()->getUser()->getAttribute('c_tipo_archivo'));
//        if(sfContext::getInstance()->getUser()->getAttribute('c_nombre_original'))
//            $this->setNombreOriginal(sfContext::getInstance()->getUser()->getAttribute('c_nombre_original'));

        return parent::save($conn);
    }
    
    public function postSave($event)
    {
        $cacheDriver = $this->getTable()->getAttribute(Doctrine_Core::ATTR_RESULT_CACHE);
        $cacheDriver->delete('correspondencia_AnexoArchivo_correspondencia_id_'.$this->get('correspondencia_id'));
    }
    
    public function postDelete($event)
    {
        $cacheDriver = $this->getTable()->getAttribute(Doctrine_Core::ATTR_RESULT_CACHE);
        $cacheDriver->delete('correspondencia_AnexoArchivo_correspondencia_id_'.$this->get('correspondencia_id'));
    }
}
