<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Organigrama_UnidadGeoreferencia', 'doctrine');

/**
 * BaseOrganigrama_UnidadGeoreferencia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $unidad_id
 * @property float $coordenadas
 * @property integer $id_update
 * @property Organigrama_Unidad $Organigrama_Unidad
 * 
 * @method integer                         getUnidadId()           Returns the current record's "unidad_id" value
 * @method float                           getCoordenadas()        Returns the current record's "coordenadas" value
 * @method integer                         getIdUpdate()           Returns the current record's "id_update" value
 * @method Organigrama_Unidad              getOrganigramaUnidad()  Returns the current record's "Organigrama_Unidad" value
 * @method Organigrama_UnidadGeoreferencia setUnidadId()           Sets the current record's "unidad_id" value
 * @method Organigrama_UnidadGeoreferencia setCoordenadas()        Sets the current record's "coordenadas" value
 * @method Organigrama_UnidadGeoreferencia setIdUpdate()           Sets the current record's "id_update" value
 * @method Organigrama_UnidadGeoreferencia setOrganigramaUnidad()  Sets the current record's "Organigrama_Unidad" value
 * 
 * @package    siglas
 * @subpackage model
 * @author     Livio Lopez
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOrganigrama_UnidadGeoreferencia extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('organigrama.unidad_georeferencia');
        $this->hasColumn('unidad_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'organigrama.unidad_georeferencia_unidad_id',
             'length' => 4,
             ));
        $this->hasColumn('coordenadas', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('id_update', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Organigrama_Unidad', array(
             'local' => 'unidad_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}