<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Inventario_Inventario', 'doctrine');

/**
 * BaseInventario_Inventario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $almacen_id
 * @property integer $articulo_id
 * @property integer $articulo_ingreso_id
 * @property float $cantidad_inicial
 * @property float $cantidad_actual
 * @property string $status
 * @property integer $id_update
 * @property string $ip_update
 * @property Inventario_Almacen $Inventario_Almacen
 * @property Inventario_Articulo $Inventario_Articulo
 * @property Inventario_ArticuloIngreso $Inventario_ArticuloIngreso
 * @property Doctrine_Collection $Inventario_ArticuloEgreso
 * 
 * @method integer                    getId()                         Returns the current record's "id" value
 * @method integer                    getAlmacenId()                  Returns the current record's "almacen_id" value
 * @method integer                    getArticuloId()                 Returns the current record's "articulo_id" value
 * @method integer                    getArticuloIngresoId()          Returns the current record's "articulo_ingreso_id" value
 * @method float                      getCantidadInicial()            Returns the current record's "cantidad_inicial" value
 * @method float                      getCantidadActual()             Returns the current record's "cantidad_actual" value
 * @method string                     getStatus()                     Returns the current record's "status" value
 * @method integer                    getIdUpdate()                   Returns the current record's "id_update" value
 * @method string                     getIpUpdate()                   Returns the current record's "ip_update" value
 * @method Inventario_Almacen         getInventarioAlmacen()          Returns the current record's "Inventario_Almacen" value
 * @method Inventario_Articulo        getInventarioArticulo()         Returns the current record's "Inventario_Articulo" value
 * @method Inventario_ArticuloIngreso getInventarioArticuloIngreso()  Returns the current record's "Inventario_ArticuloIngreso" value
 * @method Doctrine_Collection        getInventarioArticuloEgreso()   Returns the current record's "Inventario_ArticuloEgreso" collection
 * @method Inventario_Inventario      setId()                         Sets the current record's "id" value
 * @method Inventario_Inventario      setAlmacenId()                  Sets the current record's "almacen_id" value
 * @method Inventario_Inventario      setArticuloId()                 Sets the current record's "articulo_id" value
 * @method Inventario_Inventario      setArticuloIngresoId()          Sets the current record's "articulo_ingreso_id" value
 * @method Inventario_Inventario      setCantidadInicial()            Sets the current record's "cantidad_inicial" value
 * @method Inventario_Inventario      setCantidadActual()             Sets the current record's "cantidad_actual" value
 * @method Inventario_Inventario      setStatus()                     Sets the current record's "status" value
 * @method Inventario_Inventario      setIdUpdate()                   Sets the current record's "id_update" value
 * @method Inventario_Inventario      setIpUpdate()                   Sets the current record's "ip_update" value
 * @method Inventario_Inventario      setInventarioAlmacen()          Sets the current record's "Inventario_Almacen" value
 * @method Inventario_Inventario      setInventarioArticulo()         Sets the current record's "Inventario_Articulo" value
 * @method Inventario_Inventario      setInventarioArticuloIngreso()  Sets the current record's "Inventario_ArticuloIngreso" value
 * @method Inventario_Inventario      setInventarioArticuloEgreso()   Sets the current record's "Inventario_ArticuloEgreso" collection
 * 
 * @package    siglas
 * @subpackage model
 * @author     Livio Lopez
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInventario_Inventario extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('inventario.inventario');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'inventario.inventario_id',
             'length' => 4,
             ));
        $this->hasColumn('almacen_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('articulo_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('articulo_ingreso_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('cantidad_inicial', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('cantidad_actual', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('status', 'string', 1, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('id_update', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('ip_update', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Inventario_Almacen', array(
             'local' => 'almacen_id',
             'foreign' => 'id'));

        $this->hasOne('Inventario_Articulo', array(
             'local' => 'articulo_id',
             'foreign' => 'id'));

        $this->hasOne('Inventario_ArticuloIngreso', array(
             'local' => 'articulo_ingreso_id',
             'foreign' => 'id'));

        $this->hasMany('Inventario_ArticuloEgreso', array(
             'local' => 'id',
             'foreign' => 'inventario_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}