<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Acceso_ModuloPerfil', 'doctrine');

/**
 * BaseAcceso_ModuloPerfil
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $perfil_id
 * @property integer $modulo_id
 * @property string $status
 * @property integer $id_update
 * @property integer $id
 * @property Acceso_Modulo $Acceso_Modulo
 * @property Acceso_Perfil $Acceso_Perfil
 * 
 * @method integer             getPerfilId()      Returns the current record's "perfil_id" value
 * @method integer             getModuloId()      Returns the current record's "modulo_id" value
 * @method string              getStatus()        Returns the current record's "status" value
 * @method integer             getIdUpdate()      Returns the current record's "id_update" value
 * @method integer             getId()            Returns the current record's "id" value
 * @method Acceso_Modulo       getAccesoModulo()  Returns the current record's "Acceso_Modulo" value
 * @method Acceso_Perfil       getAccesoPerfil()  Returns the current record's "Acceso_Perfil" value
 * @method Acceso_ModuloPerfil setPerfilId()      Sets the current record's "perfil_id" value
 * @method Acceso_ModuloPerfil setModuloId()      Sets the current record's "modulo_id" value
 * @method Acceso_ModuloPerfil setStatus()        Sets the current record's "status" value
 * @method Acceso_ModuloPerfil setIdUpdate()      Sets the current record's "id_update" value
 * @method Acceso_ModuloPerfil setId()            Sets the current record's "id" value
 * @method Acceso_ModuloPerfil setAccesoModulo()  Sets the current record's "Acceso_Modulo" value
 * @method Acceso_ModuloPerfil setAccesoPerfil()  Sets the current record's "Acceso_Perfil" value
 * 
 * @package    siglas
 * @subpackage model
 * @author     Livio Lopez
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAcceso_ModuloPerfil extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('acceso.modulo_perfil');
        $this->hasColumn('perfil_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('modulo_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('status', 'string', 1, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('id_update', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'acceso.modulo_perfil_id',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Acceso_Modulo', array(
             'local' => 'modulo_id',
             'foreign' => 'id'));

        $this->hasOne('Acceso_Perfil', array(
             'local' => 'perfil_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}