<?php

/**
 * Extenciones_ServiciosGenerales
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    siglas-(institucion)
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Extenciones_ServiciosGenerales extends BaseExtenciones_ServiciosGenerales
{
}
