generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Correspondencia_Correspondencia
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          correspondencia_correspondencia
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        n_correspondencia_emisor: { label: N° Envio, help: Número o Nombre con el que identificará el envio. Ejemplos= DI-1223  1233  DINFOR3  D1233 }
        f_envio: { label: Fecha de Envio }
        status: { label: Estatus }
        tipo_traslado_externo: { label: Forma de envio }
        empresa_traslado: { label: Empresa contratada }
        n_guia_traslado: { label: Nº de Guia }
      list:
        table_method: innerListEnviada
        title: Correspondencia y Solicitudes enviadas
        max_per_page:   10
        #display: [n_correspondencia_emisor, _firman, _formatos, _para, f_envio, tadjuntos, tfisicos, _status, _user_update, _ultima_vista ,_acciones]
        display: [_identificacion, _documento, _detalles, _acciones]
        fields:
          tadjuntos: { label: ' ' }
          tfisicos: { label: ' ' }
          ultima_vista: { label: ' ' }
          user_update: { label: Hecho por }
        object_actions: []
        batch_actions:
          anular: {label: Anular}
          firmarEnviar: {label: Firmar y Enviar}
#          firmarEnviarCertificado: {label: Firmar y Enviar (Firma Certificada)}
        actions:
          _new: []
          excel: {label: Exportar, action: excel}
          estadisticas: {label: Estadisticas, action: estadisticas}
      filter:
        display: [n_correspondencia_emisor, f_envio, created_at, status, prioridad, hechoPor, _separador_firman, firma, _separador_receptor_externo, receptor_organismo_id, receptor_persona_id, receptor_persona_cargo_id, tipo_traslado_externo, empresa_traslado, n_guia_traslado, _separador_receptor_interno, _unidad_funcionario_filter, _separador_formatos, formato, formatoPalabra, _separador_adjuntos, adjunto, _separador_fisicos, fisico, fisicoPalabra]
        fields:
          n_correspondencia_emisor: { label: N° Envio, help: Número de correlativo }
          created_at: { label: Fecha de Creación }
          receptor_persona: { label: Dirigido a, help: Nombre de la persona externa a la que se envio }
          receptor_persona_cargo: { label: Cargo, help: Cargo de la persona externa a la que se le envio la correspondencia }
          firma: { label: Funcionario }
          formato: { label: Tipo }
          formatoPalabra: { label: Palabra o Frase }
          adjunto: { label: Nombre }
          fisico: { label: Tipo }
          fisicoPalabra: { label: Caracteristicas }
          hechoPor: {label: Hecha Por}
      form:    ~
      edit:
        title: Editar correspondencia o solicitud número <%%n_correspondencia_emisor%%>
        display: ~
        actions:
          _list: []
          _save: []
      new:
        title: Nueva correspondencia o solicitud
        display: ~
        fields:
          correlativo: { label: ' ' }
        actions:
          _list: []
          _save: []